### ISSUE TITLE
Error: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

### ISSUE THREAD

**Issue by vithanhlam** [abi/screenshot-to-code#1]
Hello, thank you for your contribution, I am having the above problem, can you help me?

` File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte`

**Comment by nongvanto** [comment]
you delete the .env file and recreate it manually, it works for me

**Comment by overflowy** [comment]
The env file you produced is not UTF_8 encoded, and Python can't read it.

**Comment by vithanhlam** [comment]
> you delete the .env file and recreate it manually, it works for me

Thank you, I opened it with notepad++ and converted it to UTF-8 and it worked
