### ISSUE TITLE
Exception in callback H11Protocol.connection_mad

### ISSUE THREAD

**Issue by azhe-w** [abi/screenshot-to-code#101]
I encountered the following error after uploading images when running the project on the command prompt.
![微信图片_20231126073507](https://github.com/abi/screenshot-to-code/assets/36022417/18953cc0-025b-44d2-840c-a656e6f5dde3)
![微信图片_20231126075630](https://github.com/abi/screenshot-to-code/assets/36022417/907d95a9-4948-4459-a4f2-724c9387fcd9)

**Comment by abi** [comment]
Could you try this? https://github.com/abi/screenshot-to-code/issues/3#issuecomment-1818520675

I don't think that's the issue, but that's possible. Could you also paste in the error into ChatGPT? I think your server is not starting up for some reason. You could also try updating the port on the frontend and the backend to something other than 7001.
