### ISSUE TITLE
WebSocket error code 

### ISSUE THREAD

**Issue by onesky2015** [abi/screenshot-to-code#103]
![ISSION](https://github.com/abi/screenshot-to-code/assets/79200118/0430ea77-da88-4eaa-b9a0-55d22c93e2d7)

**Comment by oxie** [comment]
clean clone and docker compose up, upload picture and i got the same error

**Comment by abi** [comment]
What happens when you visit 127.0.0.1?

**Comment by cwanxing** [comment]
<img width="1439" alt="image" src="https://github.com/abi/screenshot-to-code/assets/51827272/998ad717-1379-49a5-b80d-98c978b19607">

<img width="1440" alt="image" src="https://github.com/abi/screenshot-to-code/assets/51827272/58fe97d1-c8e1-4b08-9dac-63d0edd738f7">

Front normal, error reported after stop

**Comment by abi** [comment]
@cwanxing can you open a new issue and share your backend logs?
