### ISSUE TITLE
Running on Docker give me this issue

### ISSUE THREAD

**Issue by yogaics** [abi/screenshot-to-code#112]
**Error generating code. Check the Developer Console AND the backend logs for details. Feel free to open a Github issue.**

I run this command: docker-compose up -d --build
Running in windows docker.
I've check on backend and frontend log in docker but find it empty. What can I do to check for the error?

**Comment by abi** [comment]
Can you post the browser developer console logs? And docker logs should give you something.

**Comment by abi** [comment]
@vicman your issue appears to be in downloading the docker base images. It's a networking issue so I would check your internet connection, any VPNs you are using and just retrying.

**Comment by tiefengsun** [comment]
> **Error generating code. Check the Developer Console AND the backend logs for details. Feel free to open a Github issue.**
> 
> I run this command: docker-compose up -d --build Running in windows docker. I've check on backend and frontend log in docker but find it empty. What can I do to check for the error?

Same problem as ours
