### ISSUE TITLE
Error generating code. Check the Developer Console AND the backend logs for details. Feel free to open a Github issue.

### ISSUE THREAD

**Issue by ysfkarakaya** [abi/screenshot-to-code#116]
hello, I entered my api address via https://picoapps.xyz/free-tools/screenshot-to-code online demo and tested it but I get this error, there is no problem with the screenshot api. but when translating to code I get this error "Error generating code. Check the Developer Console AND backend logs for details. Feel free to open a Github issue."

**Comment by Jadenyoky** [comment]
i'm too have this proplem ..

**Comment by ftanda-go** [comment]
The product is still in its early stages and should be refined before being released to the public.

**Comment by abi** [comment]
We don't currently provide support for the hosted version. Please download the code and run it locally.

@ftanda-go what? you're free to not use a free product.
