### ISSUE TITLE
Install instructions get stuck at 'poetry install' step

### ISSUE THREAD

**Issue by milkybar1983** [abi/screenshot-to-code#12]
gets stuck on this step of script: Installing the current project: backend (0.1.0)

PS C:\screenshot-to-code-main\backend> poetry install
Creating virtualenv backend-0vQsLdXv-py3.12 in C:\Users\milky\AppData\Local\pypoetry\Cache\virtualenvs
Installing dependencies from lock file

Package operations: 21 installs, 0 updates, 0 removals

  • Installing certifi (2023.7.22)
  • Installing h11 (0.14.0)
  • Installing idna (3.4)
  • Installing sniffio (1.3.0)
  • Installing anyio (3.7.1)
  • Installing colorama (0.4.6)
  • Installing httpcore (1.0.2)
  • Installing typing-extensions (4.8.0)
  • Installing click (8.1.7)
  • Installing distro (1.8.0)
  • Installing httpx (0.25.1)
  • Installing pydantic (1.10.13)
  • Installing soupsieve (2.5)
  • Installing starlette (0.27.0)
  • Installing tqdm (4.66.1)
  • Installing beautifulsoup4 (4.12.2)
  • Installing fastapi (0.95.2)
  • Installing openai (1.2.4)
  • Installing python-dotenv (1.0.0)
  • Installing uvicorn (0.24.0.post1)
  • Installing websockets (12.0)

Installing the current project: backend (0.1.0)
The current project could not be installed: No file/folder found for package backend
If you do not want to install the current project use --no-root

**Comment by abi** [comment]
Have you tried this solution? https://github.com/abi/screenshot-to-code/issues/3#issuecomment-1814777959
