### ISSUE TITLE
Docker deploy failed due to buildkit problem

### ISSUE THREAD

**Issue by etfromchina** [abi/screenshot-to-code#120]
When I was trying to deploy docker, this happened.

docker-compose up -d --build
[+] Building 34.0s (0/1)
[+] Building 34.0s (0/1)
 => [internal] booting buildkit                                           34.0s
[+] Building 34.2s (1/1) FINISHED
 => ERROR [internal] booting buildkit                                     34.2s
 => => pulling image moby/buildkit:buildx-stable-1                        34.2s
 => => creating container buildx_buildkit_default                          0.0s
[+] Building 34.2s (1/1) FINISHED
 => CANCELED [internal] booting buildkit                                  34.2s
 => => pulling image moby/buildkit:buildx-stable-1                        34.2s
 => => creating container buildx_buildkit_default                          0.0s
Error response from daemon: Conflict. The container name "/buildx_buildkit_default" is already in use by container "8c2af9bd48c75b0ba00bd00eb5b9fdf441669d49390e5a0dd9da21319bc52dc1". You have to remove (or rename) that container to be able to reuse that name.

I've tried a couple of times, and this still happens.

**Comment by abi** [comment]
As the error message says, "You have to remove (or rename) that container to be able to reuse that name." I would try to clear out some of the other containers you have on Docker

**Comment by etfromchina** [comment]
> As the error message says, "You have to remove (or rename) that container to be able to reuse that name." I would try to clear out some of the other containers you have on Docker

Do you mean I have to clear out all the containers on my docker? But I only "zhayujie/chatgpt-on-wechat" and "portainer_agent", nothing else. After the first failed deployment of screenshot-to-code, a container called "buildx_buildkit_default" showed up but not running. When I delete it and then deploy screenshot-to-code again, the same warning messager pops up again.

**Comment by etfromchina** [comment]
the point is why it shows "ERROR [internal] booting buildkit 34.2s" and then it has been cancelled automatically?

**Comment by abi** [comment]
Were you able to get this working?

**Comment by etfromchina** [comment]
![1701868220288](https://github.com/abi/screenshot-to-code/assets/124589551/ddc37141-6c23-4dca-a691-590bc0b4a542)
no, same problem happened.

**Comment by etfromchina** [comment]
I deleted the container and the image and rebuilt it again, and then this happened.
![image](https://github.com/abi/screenshot-to-code/assets/124589551/ca6e3629-1f26-40a7-8aa7-5bd008b1c25c)

**Comment by etfromchina** [comment]
I've tried VPN and even different servers, and the same thing happens.
![image](https://github.com/abi/screenshot-to-code/assets/124589551/3c4fcf3a-e04e-4312-8181-f8fff03a5d33)

**Comment by abi** [comment]
Can you try running it without docker? Or use the hosted version.

**Comment by abi** [comment]
Lol great!

**Comment by etfromchina** [comment]
I've finally found the reason why docker didn't work!
BuildKit did something bad about it. So just run the following codes:
```
export DOCKER_BUILDKIT=0
docker-compose up -d
```
Problem solved.

**Comment by etfromchina** [comment]
BuildKit is Docker's next-generation build engine that delivers faster, more reliable builds.
If you see the buildx_buildkit_default container already exists error immediately after running the docker-compose up -d command, it may be because BuildKit created this container during the build process but did not delete it in time after the build was completed.
You can try turning off Docker's BuildKit function to see if that solves the problem. BuildKit can be turned off by setting the environment variable DOCKER_BUILDKIT=0.
