### ISSUE TITLE
pre-hosted version throwing 'Connection closed 1006 ' error

### ISSUE THREAD

**Issue by milkybar1983** [abi/screenshot-to-code#13]
Connecting to backend @  wss://backend-screenshot-to-code.onrender.com/generate-code
index-6038cf45.js:225 Connection closed 1006 
index-6038cf45.js:225 WebSocket error code CloseEvent
(anonymous) @ index-6038cf45.js:225

API key is correct and has access and credits

**Comment by milkybar1983** [comment]
Edge browser works

**Comment by abi** [comment]
At the moment, I'm not going to spend too much time investigating hosted version issues. You can run it locally if that's not working.
