### ISSUE TITLE
Why Connection closed 1006

### ISSUE THREAD

**Issue by DengJianShen** [abi/screenshot-to-code#132]
![image](https://github.com/abi/screenshot-to-code/assets/19514719/e8d6aa4c-e133-475d-bce6-7309082c0cc2)

![image](https://github.com/abi/screenshot-to-code/assets/19514719/9e00d1ef-67e2-4e13-9276-4ea4119c12cc)

![image](https://github.com/abi/screenshot-to-code/assets/19514719/a15e37ce-d0aa-4dfe-896d-3eb0a96a7e63)

**Comment by abi** [comment]
Can you try running it locally?

I'm going to improve the error messages on the hosted version but right now, there's minimal logging on the hosted version. Or you can buy an access code. That will work.

**Comment by Jadenyoky** [comment]
![Screenshot_2](https://github.com/abi/screenshot-to-code/assets/53493986/b2ae7994-f6da-44b6-9a8c-de3fde539af4)
i run it from github project and run backend on 7001 and frontend on 5173 port .. and still same proplem with run on docker or the main website ...

**Comment by Jadenyoky** [comment]
i have subscription and 5 dollars credit free not usage yet
![Screenshot_3](https://github.com/abi/screenshot-to-code/assets/53493986/52890428-3ff7-43a8-b973-987c5b13d45d)

**Comment by abi** [comment]
Some times it takes a few minutes for the credits to update but I assume it's been a while. 

Can you share backend logs when you run it locally?

**Comment by Jadenyoky** [comment]
that's logs in console log in chrome and terminal in vscode
![Screenshot_5](https://github.com/abi/screenshot-to-code/assets/53493986/ed0a90fc-9fed-4399-a2df-535125643934)
![Screenshot_4](https://github.com/abi/screenshot-to-code/assets/53493986/bb64aedb-4692-426d-8520-f1c6816b775b)

**Comment by abi** [comment]
As you can see on the last line, your api key doesn't have access to vision. I'm not sure but I would double check all the steps outlined here: https://github.com/abi/screenshot-to-code/blob/main/Troubleshooting.md

**Comment by jaychoubaby** [comment]
I also have the same problem.

**Comment by yuhe0925** [comment]
connection closed 1000

the code is not completed

**Comment by abi** [comment]
Can yall please share you backend and front end logs from your terminal? That will help me debug the issue.

**Comment by abi** [comment]
Feel free to re-open if there are still issues. We have improved the error messages quite a bit so it should tell you what the issue is with your API key
