### ISSUE TITLE
error generating code 

### ISSUE THREAD

**Issue by VickyRegin1994** [abi/screenshot-to-code#136]
Error generating code. Check the Developer Console AND the backend logs for details. Feel free to open a Github issue.

while hiiting the url and pasting the screenshot it shows below error ,am i doing it correctly 
<img width="940" alt="Screenshot 2023-11-30 212304" src="https://github.com/abi/screenshot-to-code/assets/152517537/38d9b1af-125b-45d4-9c4a-cbb600f5ec7d">
<img width="940" alt="Screenshot 2023-11-30 212304" src="https://github.com/abi/screenshot-to-code/assets/152517537/9c5bf85b-8109-44f7-842d-ec69dd2c49d0">

**Comment by abi** [comment]
Did you follow the instructions to get an OpenAI key here? https://github.com/abi/screenshot-to-code/blob/main/Troubleshooting.md Or you can buy generation credits.

**Comment by abi** [comment]
Is it not. You can use your own key. But follow the instructions to get vision access. Are you Tier 1?

**Comment by VickyRegin1994** [comment]
CURRENT TIER
Free

**Comment by abi** [comment]
See https://github.com/abi/screenshot-to-code/blob/main/Troubleshooting.md
