### ISSUE TITLE
Error generating code.

### ISSUE THREAD

**Issue by gospodinsreda** [abi/screenshot-to-code#14]
Error generating code. Check the Developer Console for details. Feel free to open a Github issue

What could be the problem, can you please tell me?

**Comment by abi** [comment]
Are you running this locally? If so, can you check the output of the backend?

**Comment by gospodinsreda** [comment]
> Are you running this locally? If so, can you check the output of the backend server?

No, I tried using the [online version](https://picoapps.xyz/free-tools/screenshot-to-code)
And I get the error I described above(

**Comment by abi** [comment]
Does your API key have access to the vision model?

**Comment by gospodinsreda** [comment]
> Does your API key have access to the vision model?

See also. I have a Plus subscription and can safely use GPT4-Vision in the main chat. I have generated an API key in my account and use it. Could you please tell me if I need to perform additional manipulations when generating the API key?

**Comment by abi** [comment]
Please see the FAQs section on the README

**Comment by vietpro230** [comment]
I am getting error
cannot be loaded because running scripts is disabled on this system. For more information, see about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170.
Can you help me fix it?

**Comment by abi** [comment]
At the moment, I'm not going to spend too much time investigating hosted version issues. You can run it locally if that's not working.

**Comment by d1v1ng1sC00l** [comment]
On the online version, I solved it by opening a private window. must be an extension from the client side blocking it.
