### ISSUE TITLE
My account have gpt4 access but backend showed "model not found" error message

### ISSUE THREAD

**Issue by mio-19** [abi/screenshot-to-code#142]
```
backend-1   | openai.NotFoundError: Error code: 404 - {'error': {'message': 'The model `gpt-4-vision-preview` does not exist or you do not have access to it. Learn more: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}
```

GPT4 access
![image](https://github.com/abi/screenshot-to-code/assets/57285379/a9804218-181a-441c-aa45-e3295cfd6074)

**Comment by juanchistosomk** [comment]
Primero tiene que ponerle la API de ChatGTP-4, en otras palabras, para usar este programa debe comprar una licencia de la API de ChatGTP4

**Comment by dhtkak104** [comment]
![스크린샷 2023-12-13 오후 1 08 27](https://github.com/abi/screenshot-to-code/assets/41221746/8b7e37c9-a3e3-431c-b9d4-ce1754568c4d)

**Comment by dhtkak104** [comment]
I purchased a tier 1 license, but I am encountering the following error.

Error code: 404 - {'error': {'message': 'The model `gpt-4-vision-preview` does not exist or you do not have access to it. Learn more: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}. Please make sure you have followed the instructions correctly to obtain an OpenAI key with GPT vision access: https://github.com/abi/screenshot-to-code/blob/main/Troubleshooting.md Alternatively, you can purchase code generation credits directly on this website
