### ISSUE TITLE
Connection closed 1006

### ISSUE THREAD

**Issue by hesoso** [abi/screenshot-to-code#146]
I can't recharge my OpenAI account, so I configured a third-party interface and token in the environment variables. They work well on my browser's translation plugin, but they cause errors here.

browser console:
<img width="1249" alt="WX20231201-165603@2x" src="https://github.com/abi/screenshot-to-code/assets/16646331/6f3ef438-e5b8-4e1c-9590-a8546270dc76">

backend shell:

> Using OpenAI API key from client-side settings dialog
> Using OpenAI Base URL from client-side settings dialog
> generating code...
> ERROR:    Exception in ASGI application
> Traceback (most recent call last):
>   File "/Users/hesoso/Library/Caches/pypoetry/virtualenvs/backend-OF4-y6Ak-py3.12/lib/python3.12/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 247, in run_asgi
>     result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/hesoso/Library/Caches/pypoetry/virtualenvs/backend-OF4-y6Ak-py3.12/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
>     return await self.app(scope, receive, send)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/hesoso/Library/Caches/pypoetry/virtualenvs/backend-OF4-y6Ak-py3.12/lib/python3.12/site-packages/fastapi/applications.py", line 276, in __call__
>     await super().__call__(scope, receive, send)
>   File "/Users/hesoso/Library/Caches/pypoetry/virtualenvs/backend-OF4-y6Ak-py3.12/lib/python3.12/site-packages/starlette/applications.py", line 122, in __call__
>     await self.middleware_stack(scope, receive, send)
>   File "/Users/hesoso/Library/Caches/pypoetry/virtualenvs/backend-OF4-y6Ak-py3.12/lib/python3.12/site-packages/starlette/middleware/errors.py", line 149, in __call__
>     await self.app(scope, receive, send)
>   File "/Users/hesoso/Library/Caches/pypoetry/virtualenvs/backend-OF4-y6Ak-py3.12/lib/python3.12/site-packages/starlette/middleware/cors.py", line 75, in __call__
>     await self.app(scope, receive, send)
>   File "/Users/hesoso/Library/Caches/pypoetry/virtualenvs/backend-OF4-y6Ak-py3.12/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
>     raise exc
>   File "/Users/hesoso/Library/Caches/pypoetry/virtualenvs/backend-OF4-y6Ak-py3.12/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
>     await self.app(scope, receive, sender)
>   File "/Users/hesoso/Library/Caches/pypoetry/virtualenvs/backend-OF4-y6Ak-py3.12/lib/python3.12/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
>     raise e
>   File "/Users/hesoso/Library/Caches/pypoetry/virtualenvs/backend-OF4-y6Ak-py3.12/lib/python3.12/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
>     await self.app(scope, receive, send)
>   File "/Users/hesoso/Library/Caches/pypoetry/virtualenvs/backend-OF4-y6Ak-py3.12/lib/python3.12/site-packages/starlette/routing.py", line 718, in __call__
>     await route.handle(scope, receive, send)
>   File "/Users/hesoso/Library/Caches/pypoetry/virtualenvs/backend-OF4-y6Ak-py3.12/lib/python3.12/site-packages/starlette/routing.py", line 341, in handle
>     await self.app(scope, receive, send)
>   File "/Users/hesoso/Library/Caches/pypoetry/virtualenvs/backend-OF4-y6Ak-py3.12/lib/python3.12/site-packages/starlette/routing.py", line 82, in app
>     await func(session)
>   File "/Users/hesoso/Library/Caches/pypoetry/virtualenvs/backend-OF4-y6Ak-py3.12/lib/python3.12/site-packages/fastapi/routing.py", line 289, in app
>     await dependant.call(**values)
>   File "/Users/hesoso/Desktop/screenshot-to-code/backend/main.py", line 175, in stream_code
>     completion = await stream_openai_response(
>                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/hesoso/Desktop/screenshot-to-code/backend/llm.py", line 26, in stream_openai_response
>     completion = await client.chat.completions.create(**params)
>                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/hesoso/Library/Caches/pypoetry/virtualenvs/backend-OF4-y6Ak-py3.12/lib/python3.12/site-packages/openai/resources/chat/completions.py", line 1191, in create
>     return await self._post(
>            ^^^^^^^^^^^^^^^^^
>   File "/Users/hesoso/Library/Caches/pypoetry/virtualenvs/backend-OF4-y6Ak-py3.12/lib/python3.12/site-packages/openai/_base_client.py", line 1474, in post
>     return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/hesoso/Library/Caches/pypoetry/virtualenvs/backend-OF4-y6Ak-py3.12/lib/python3.12/site-packages/openai/_base_client.py", line 1275, in request
>     return await self._request(
>            ^^^^^^^^^^^^^^^^^^^^
>   File "/Users/hesoso/Library/Caches/pypoetry/virtualenvs/backend-OF4-y6Ak-py3.12/lib/python3.12/site-packages/openai/_base_client.py", line 1318, in _request
>     raise self._make_status_error_from_response(err.response) from None
> openai.APIStatusError: Error code: 307
> INFO:     connection closed

**Comment by yimingsun12138** [comment]
same error, I am sure that my OpenAI token is available for gpt 4 vision

**Comment by 1766095699** [comment]
> same error, I am sure that my OpenAI token is available for gpt 4 vision

me too.

**Comment by seven2202** [comment]
需要在./frontend文件中配置VITE_WS_BACKEND_URL=ws://IP_address:7001。这里的IP_address应该配置为外部IP。
更新代码后，需要运行 docker-compose up -d --build

**Comment by hesoso** [comment]
> 需要在./frontend文件中配置VITE_WS_BACKEND_URL=ws://IP_address:7001。这里的IP_address应该配置为外部IP。 更新代码后，需要运行 docker-compose up -d --build

直接在本地启动的，没有使用docker呢

**Comment by xjspace** [comment]
> > 需要在./frontend文件中配置VITE_WS_BACKEND_URL=ws://IP_address:7001。这里的IP_address应该配置为外部IP。 更新代码后，需要运行 docker-compose up -d --build
> 
> 直接在本地启动的，没有使用docker呢

无论是否使用docker 目前那个ip_address 的用外网ip ，局域网IP是不行的

**Comment by hesoso** [comment]
> > > 需要在./frontend文件中配置VITE_WS_BACKEND_URL=ws://IP_address:7001。这里的IP_address应该配置为外部IP。 更新代码后，需要运行 docker-compose up -d --build
> > 
> > 
> > 直接在本地启动的，没有使用docker呢
> 
> 无论是否使用docker 目前那个ip_address 的用外网ip ，局域网IP是不行的

可是我的服务不是启动在本机的嘛？按理这里前端websocket连的应该127.0.0.1吗没问题才对啊？

**Comment by seven2202** [comment]
First of all, are you using a transit or direct connection?  Second, check whether the key is normal.  1006 does not necessarily mean that the backend cannot be connected, and if the api address is connected incorrectly, an error of 1006 will be reported.  Finally, if you are using transit, you need to add /v1.

**Comment by hesoso** [comment]
> First of all, are you using a transit or direct connection? Second, check whether the key is normal. 1006 does not necessarily mean that the backend cannot be connected, and if the api address is connected incorrectly, an error of 1006 will be reported. Finally, if you are using transit, you need to add /v1.

I am using a transit connection, and I have configured OPENAI_BASE_URL=https://xxxx/v1 and the key, but it still prompts error code 1006. When I don't add the /v1 suffix, it gives error 1000, and there are no errors reported, but the file I receive contains no content.

**Comment by seven2202** [comment]
Do you have a proxy server on? If yes, close it.

**Comment by seven2202** [comment]
> > 首先，您使用的是中转还是直达？其次，检查按键是否正常。1006并不一定意味着后端无法连接，如果api地址连接错误，会报1006的错误。最后，如果您使用的是中转，则需要添加/v1。
> 
> 我使用的是中转连接，并且已经配置了 OPENAI_BASE_URL= https://xxxx/v1和密钥，但仍然提示错误代码 1006。当我不添加 /v1 后缀时，它给出错误 1000，并且有没有报告错误，但我收到的文件不包含任何内容。

Do you have a proxy server on? If yes, close it.
