### ISSUE TITLE
API ChatGPT-4 Error

### ISSUE THREAD

**Issue by juanchistosomk** [abi/screenshot-to-code#149]
Me sali este error:
openai.RateLimitError: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Yo tengo plan de Pago por uso con un saldo de 10 dolares
<img width="946" alt="Captura de pantalla 2023-12-01 140027" src="https://github.com/abi/screenshot-to-code/assets/36779031/866d0585-107f-4c32-9a43-7984f2f21bba">

**Comment by abi** [comment]
Can you check your tier? https://github.com/abi/screenshot-to-code/blob/main/Troubleshooting.md
