### ISSUE TITLE
Error generating code. Check the Developer Console AND the backend logs for details

### ISSUE THREAD

**Issue by SmartWebCodder** [abi/screenshot-to-code#150]
My ChatGPT has access to GPT-VISION. and the web app loads well but when I upload an image. it returns this error 'Error generating code. Check the Developer Console AND the backend logs for details'
<img width="466" alt="error" src="https://github.com/abi/screenshot-to-code/assets/100529823/97c337b7-de54-45f9-8def-f984ade50a6d">

**Comment by ranmaolin** [comment]
I have same issues , I already entered API key

**Comment by SmartWebCodder** [comment]
Did it work when you entered API Key?

**Comment by jacquesmats** [comment]
Take a look here, maybe you are missing the .env file in the frontend:
https://github.com/abi/screenshot-to-code/issues/155#issuecomment-1837482503

**Comment by SmartWebCodder** [comment]
still same error.

**Comment by yxf-git** [comment]
I have same issues , I already entered API key

**Comment by AnAnonymousFriend** [comment]
I have the same error, but my error only exists in docker

**Comment by abi** [comment]
@AnAnonymousFriend please share your docker logs to help debug it.

**Comment by AnAnonymousFriend** [comment]
@abi  When I added "--host 0.0.0.0", docker worked fine

**Comment by abi** [comment]
Great!
