### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by robin-collins** [abi/screenshot-to-code#152]
I had a look at your repo today, and got it up and running via docker locally, Looked great. I saw you had an integration for https://screenshotone.com/ to allow entry of a url instead of an image. This is great but could you consider also supporting ws-screenshot (https://github.com/elestio/ws-screenshot/). I have used it for quite some time and it works wonderfully, and being self hosted with an api makes it free

**Comment by abi** [comment]
Would love to support this. So this project allows you to take the screenshot locally?
