### ISSUE TITLE
No file/folder found for package backend

### ISSUE THREAD

**Issue by ouxujia728ou** [abi/screenshot-to-code#159]
############## backend % poetry install
Installing dependencies from lock file

No dependencies to install or update

Installing the current project: backend (0.1.0)
The current project could not be installed: No file/folder found for package backend
If you do not want to install the current project use --no-root

**Comment by ouxujia728ou** [comment]
![Uploading 截屏2023-12-02 下午12.16.04.png…]()

**Comment by jacquesmats** [comment]
You can find the answer here: https://github.com/abi/screenshot-to-code/issues/3#issuecomment-1814777959
