### ISSUE TITLE
Hhhhelp! Code generation failure,Connection closed 1000

### ISSUE THREAD

**Issue by seven2202** [abi/screenshot-to-code#162]
The console reports the following error:
![image](https://github.com/abi/screenshot-to-code/assets/111497407/bf9bf3a9-1703-4164-8c4f-46bf7dcc65e8)
backend logs:
![image](https://github.com/abi/screenshot-to-code/assets/111497407/c213e504-a987-4005-bd56-6bebf1626d6f)

I just pull the code, install the dependency, and start.  The api key and base url are configured on the page 

Please help me solve this problem.
thanks ~

**Comment by Vang-z** [comment]
same problem with you, could you provide the fix way? thx❤️

**Comment by abi** [comment]
@Vang-z please open a new issue and share your front-end and back-end logs
