### ISSUE TITLE
OpenAI API Key

### ISSUE THREAD

**Issue by TurbooGhost** [abi/screenshot-to-code#172]
Hello! First of all, I must say, the work you're doing is truly impressive! 😊

I'm a subscriber to the ChatGPT Plus plan and I have a query regarding API key integration. My understanding is that I should navigate to the [API keys](https://platform.openai.com/api-keys) section on the OpenAI platform, select **Create new secret key** and then copy this new key into the OpenAI API key section on a specific webpage. Is this the correct process?

However, I encountered an issue when I followed these steps. Upon entering the new key, I received the following error message:

<code>"Error code: 404 - {'error': {'message': 'The model `gpt-4-vision-preview` does not exist or you do not have access to it. Learn more: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}. Please make sure you have followed the instructions correctly to obtain an OpenAI key with GPT vision access: https://github.com/abi/screenshot-to-code/blob/main/Troubleshooting.md Alternatively, you can purchase code generation credits directly on this website."</code>

**Comment by abi** [comment]
Have you followed the instructions here? https://github.com/abi/screenshot-to-code/blob/main/Troubleshooting.md
