### ISSUE TITLE
Vue support

### ISSUE THREAD

**Issue by 386qt** [abi/screenshot-to-code#175]
Can't find vue options, they are all html and others

**Comment by zjr71163356** [comment]
same question

**Comment by abi** [comment]
Sorry about this - I had experimental Vue support that I hadn't pushed yet. Will work on getting it out this week. Still needs some tweaks.

**Comment by chaos-zhu** [comment]
> Sorry about this - I had experimental Vue support that I hadn't pushed yet. Will work on getting it out this week. Still needs some tweaks.
I can't wait for it.

**Comment by fushengss** [comment]
Whether vue is already supported

**Comment by fushengss** [comment]
Whether vue is already supported

**Comment by jiawei666** [comment]
is it support now? @abi
