### ISSUE TITLE
Why can my API key be used on https://screenshot-to-code.com/, but I can't use it locally?

### ISSUE THREAD

**Issue by tpjaord1983** [abi/screenshot-to-code#182]
Why can my API key be used on https://screenshot-to-code.com/, but I can't use it locally?
show me this error:
Error generating code. Check the Developer Console AND the backend logs for details. Feel free to open a Github issue.

**Comment by abi** [comment]
You'll need share ALL your local logs for help with debugging this.

**Comment by tpjaord1983** [comment]
> You'll need share ALL your local logs for help with debugging this.

![error](https://github.com/abi/screenshot-to-code/assets/36291579/fe070469-d63e-46fe-b2c1-0537a3cc9676)
[localhost-1702432050122.log](https://github.com/abi/screenshot-to-code/files/13654940/localhost-1702432050122.log)
[localhost-1702432056211.log](https://github.com/abi/screenshot-to-code/files/13654941/localhost-1702432056211.log)
[localhost-1702432065310.log](https://github.com/abi/screenshot-to-code/files/13654942/localhost-1702432065310.log)

**Comment by abi** [comment]
@tpjaord1983 what bout the backend logs?

**Comment by tpjaord1983** [comment]
> @tpjaord1983 what bout the backend logs?

how can i find backend logs?

**Comment by abi** [comment]
Are you running the backend? Please see the README.

**Comment by tpjaord1983** [comment]
> Are you running the backend? Please see the README.
yes
![111](https://github.com/abi/screenshot-to-code/assets/36291579/82e23332-e165-4e86-b625-ea0893ae9467)
![222](https://github.com/abi/screenshot-to-code/assets/36291579/a572c96c-3070-42b1-ace5-ab198c38e051)

**Comment by tpjaord1983** [comment]
> Are you running the backend? Please see the README.

i find it.

I misspelled the port number for the startup run.
