### ISSUE TITLE
WebSocket connection to wss failed

### ISSUE THREAD

**Issue by robdex** [abi/screenshot-to-code#184]
Hi there,

I'm currently attempting to run your application in a secure configuration. I've set up custom URLs to proxy the localhost addresses for the frontend and backend, specifically mapping http://localhost:5371/ to https://screenshot-to-code.test/ and http://localhost:7001/ to https://screenshot-to-code-be.test/. Additionally, I've updated the frontend/.env.local file with the following:

```
VITE_WS_BACKEND_URL=wss://screenshot-to-code-be.test
```

I'm using Docker, and both the frontend and backend seem to be running correctly. However, when I attempt to upload an image, I encounter the following error:

```
Connecting to backend @ wss://screenshot-to-code-be.test/generate-code
WebSocket connection to 'wss://screenshot-to-code-be.test/generate-code' failed:
WebSocket error Event {isTrusted: true, type: 'error', target: WebSocket, currentTarget: WebSocket, eventPhase: 2, ...}
Connection closed with code 1006
WebSocket error code CloseEvent {isTrusted: true, wasClean: false, code: 1006, reason: '', type: 'close', ...}
```

Any help appreciated.

Many thanks.

**Comment by Zakirzhan** [comment]
+++

**Comment by xinatcg** [comment]
same with cloud version when try to update

**Comment by abi** [comment]
@xinatcg For the cloud version, we don't provide support if you use your own API key. Please purchase a subscription instead. If you're having trouble with the local version, I can help you and Github is the right place for support.

**Comment by xinatcg** [comment]
> @xinatcg For the cloud version, we don't provide support if you use your own API key. Please purchase a subscription instead. If you're having trouble with the local version, I can help you and Github is the right place for support.

ah. ok, so the cloud version only support generate once and cannot do update operation right?

**Comment by abi** [comment]
No it can do everything, just have to use your own OpenAI key or buy a subscription.

**Comment by xinatcg** [comment]
i used my own open api key, but when try to update after initial generate code, get error and the console show the error about the wss
