### ISSUE TITLE
One-click deployment solution based on WeQing delivery system, contributing to the community

### ISSUE THREAD

**Issue by w7team** [abi/screenshot-to-code#187]
【Screenshot to Code】这个简单的应用程序将截图转换为代码（HTML/Tailwind CSS，或React或Vue或Bootstrap）。它使用GPT-4 Vision生成代码，并使用DALL-E 3生成类似的图片。现在您还可以输入URL来克隆一个活动网站！ 
   
安装地址：https://console.w7.cc/api/deploy/thirdparty_cd/redirect?route=/zpk-install?path=https%3A%2F%2Fzpk.w7.cc%2Frespo%2Finfo%2Fchatgpt_screenshottocode

说明：安装地址为一键部署方案，服务器环境基于k3s，微擎交付系统是管理k3s的控制面板，可视化一键管理基于k3s部署的应用

【Screenshot to Code】This simple application converts screenshots into code (HTML/Tailwind CSS, React, Vue, or Bootstrap). It utilizes GPT-4 Vision to generate the code and DALL-E 3 to generate similar images. Now, you can also input a URL to clone an active website!

Installation Link: https://console.w7.cc/api/deploy/thirdparty_cd/redirect?route=/zpk-install?path=https%3A%2F%2Fzpk.w7.cc%2Frespo%2Finfo%2Fchatgpt_screenshottocode

Note: The installation link provides a one-click deployment solution. The server environment is based on k3s, and the Micro-WeChat delivery system is a control panel for managing k3s, allowing for the visual one-click management of applications deployed on k3s.

**Comment by abi** [comment]
Is the deployment system open source?

**Comment by w7team** [comment]
k3s open source,but this control system(WeQing delivery system) is saas service

**Comment by abi** [comment]
Not going to promote it here then.
