### ISSUE TITLE
Error generating code. Check the Developer Console AND the backend logs for details. Feel free to open a Github issue.

### ISSUE THREAD

**Issue by Manchuker1120** [abi/screenshot-to-code#191]
Error generating code. Check the Developer Console AND the backend logs for details. Feel free to open a Github issue.
<img width="1417" alt="image" src="https://github.com/abi/screenshot-to-code/assets/55781701/4d5c7bd7-f6d0-47ec-8f04-8733bf1c04eb">
<img width="659" alt="image" src="https://github.com/abi/screenshot-to-code/assets/55781701/0b06389e-f8c9-4f4f-b554-18a4ae8a7e3e">

**Comment by abi** [comment]
Are you running this locally or on a remote server? If it's a remote server, you need to update frontend/.env with the IP of your server

**Comment by Manchuker1120** [comment]
thank u
