### ISSUE TITLE
Create Google Colab version

### ISSUE THREAD

**Issue by aarvndhNG** [abi/screenshot-to-code#192]
Is there any colab version?

**Comment by abi** [comment]
There isn't. If someone wants to build it, I can link it from the README but it probably won't be a core part of this project since that would have to be maintained separately from the main codebase.

**Comment by aarvndhNG** [comment]
Okay i think i can try tho

**Comment by abi** [comment]
If you follow the code in generate_code.py, it should be relatively straightforward.
