### ISSUE TITLE
GPT-4 Api key not working

### ISSUE THREAD

**Issue by MominIqbal-1234** [abi/screenshot-to-code#195]
![Screenshot (256)](https://github.com/abi/screenshot-to-code/assets/61788052/1792ba49-581a-4742-b800-2f730ac14d18)

i add the key .env file

**Comment by abi** [comment]
Looks like you're trying to grab a screenshot using a URL, for that you need to sign up for https://screenshotone.com/

Or you can take the screenshot yourself, and just drag/drop it.
