### ISSUE TITLE
Error generating code.  Check the Developer Console AND the backend logs for details.  Feel free to open a Github issue.

### ISSUE THREAD

**Issue by tm1233** [abi/screenshot-to-code#196]
Error generating code.  Check the Developer Console AND the backend logs for details.  Feel free to open a Github issue.

**Comment by abi** [comment]
Paste "Developer Console AND the backend logs"

**Comment by mohanvaidya** [comment]
![Screenshot 2023-12-22 210205](https://github.com/abi/screenshot-to-code/assets/131249018/4ea83a9d-164d-4c8e-a871-11a6257e604f)

**Comment by tm1233** [comment]
> 贴"开发商控制台和后台日志"

Thank you. I've solved the problem

**Comment by r1FundsFunClub** [comment]
> > 贴"开发商控制台和后台日志"
> 
> Thank you. I've solved the problem

嗨，你是怎样解决这个问题？可以分享吗？

**Comment by silasmariusz** [comment]
how did you fix it?

**Comment by abi** [comment]
@silasmariusz can you share your logs?

**Comment by sgr2579** [comment]
How you solve this i am also getting same error in  Developer Console

**Comment by abi** [comment]
Going to close this as stale. @sgr2579 feel free to open a new ticket and share your logs.
