### ISSUE TITLE
Error generating code: Failed at backend server stating — The model `gpt-4-vision-preview` does not exist

### ISSUE THREAD

**Issue by logeshpaul** [abi/screenshot-to-code#2]
<img width="702" alt="image" src="https://github.com/abi/screenshot-to-code/assets/41541/a66a404e-8acb-4415-89ac-4d1e7d4dc194">

Error on backend: gpt-4-vision-preview does not exist or you dont have access to it.

<img width="1228" alt="image" src="https://github.com/abi/screenshot-to-code/assets/41541/ecf3310b-034b-4088-a5ba-c01bc7fe3d47">

Any idea how to resolve this error?

**Comment by JulianIsrael** [comment]
You need to buy at least 1$ of credit in https://platform.openai.com/account/billing/overview to enable the models for API usage.
