### ISSUE TITLE
No code is generated, and the display is blank.

### ISSUE THREAD

**Issue by move132** [abi/screenshot-to-code#204]
<img width="1784" alt="image" src="https://github.com/abi/screenshot-to-code/assets/9524778/fcf300f2-6087-42d9-8a20-8b5c94b3c7a9">

logs
<img width="623" alt="image" src="https://github.com/abi/screenshot-to-code/assets/9524778/f5108c6b-e48c-44c3-acf4-fdc9ff976c06">

**Comment by mxiaoyuer123** [comment]
me to

**Comment by mxiaoyuer123** [comment]
I'm like that too, it doesn't generate any code
