### ISSUE TITLE
Customize the OpenAI Base URL

### ISSUE THREAD

**Issue by luy98** [abi/screenshot-to-code#209]
I hope I can customize the OpenAI Base URL, which is https://api.openai.com/v1

**Comment by abi** [comment]
You can in the setting dialog

**Comment by luy98** [comment]
> You can in the setting dialog

But I really didn’t find it on the  setting dialog. I know there is it in the code.

**Comment by abi** [comment]
@luy98 are you using the hosted version or local version? 

<img width="495" alt="Screenshot 2024-01-08 at 5 16 59 PM" src="https://github.com/abi/screenshot-to-code/assets/23818/940d3c6e-eb49-4098-a882-39eb8cfbf06c">

**Comment by luy98** [comment]
> @luy98
> 
> <img alt="Screenshot 2024-01-08 at 5 16 59 PM" width="495" src="https:private-user-images.githubusercontent.com/23818/295074248-940d3c6e-eb49-4098-a882-39eb8cfbf06c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tI iwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3NjM3MzgsIm5iZiI6MTcwNDc2MzQzOCwicGF0aCI6Ii8yMzgxOC8yOTUwNzQyNDgtOTQwZDNj NmUtZWI0OS00MDk4LWE4ODItMzllYjhjZmJmMDZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMk Z1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDAxMjM1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkYzM4MzlhOWRjOTIyODUxNDNjY jIyOTE0OWJkOTNiM2IxMmUyMjAzYjA3OTBkMTY1NTJiZWJjMGM4MzJkNjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8aTiUz1 OBzpIM6feV6RJEfX0muFv4jgeUplHtM4ZMbk">



> @luy98
> 
> <img alt="Screenshot 2024-01-08 at 5 16 59 PM" width="495" src="https://private-user-images.githubusercontent.com/23818/295074248-940d3c6e-eb49-4098-a882-39eb8cfbf06c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3NjM3MzgsIm5iZiI6MTcwNDc2MzQzOCwicGF0aCI6Ii8yMzgxOC8yOTUwNzQyNDgtOTQwZDNjNmUtZWI0OS00MDk4LWE4ODItMzllYjhjZmJmMDZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDAxMjM1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkYzM4MzlhOWRjOTIyODUxNDNjYjIyOTE0OWJkOTNiM2IxMmUyMjAzYjA3OTBkMTY1NTJiZWJjMGM4MzJkNjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8aTiUz1OBzpIM6feV6RJEfX0muFv4jgeUplHtM4ZMbk">

Ok I get it, I'm using screenshottocode.com, not the version built from code

**Comment by abi** [comment]
The online version doesn't support custom OpenAI URLs due to security issues. My server will be calling a random URL.

**Comment by abi** [comment]
Run it locally.
