### ISSUE TITLE
Is that supported with Figma?

### ISSUE THREAD

**Issue by tianxiuali** [abi/screenshot-to-code#211]
Is the screenshot-to-code supported with Figma?
I like the screenshot-to-code. But I want a Figma plugin to generate code.
I've tried some plugins, such as Anima, Figma to Code. But the code quality is not good.

**Comment by abi** [comment]
Thanks for the request. You can right click an artboard in Figma and copy it as an image and paste it into screenshot to code

**Comment by tianxiuali** [comment]
> Thanks for the request. You can right click an artboard in Figma and copy it as an image and paste it into screenshot to code

Thank you!
