### ISSUE TITLE
I have subscribed to the hobby one, but now I want to see how many credit left I have, I open setting and it says I need to subscribe again

### ISSUE THREAD

**Issue by ahmedomar365** [abi/screenshot-to-code#212]
![image](https://github.com/abi/screenshot-to-code/assets/70892817/2b58054f-272d-4cb7-a590-39ea9cb3f54a)

**Comment by ahmedomar365** [comment]
![image](https://github.com/abi/screenshot-to-code/assets/70892817/bdb9a8b9-51a5-400b-9849-11d16f1407e3)

**Comment by abi** [comment]
You should be able to see the credits left now.
