### ISSUE TITLE
Flutter integration

### ISSUE THREAD

**Issue by ji4a** [abi/screenshot-to-code#214]
Please add Flutter integration. Screenshot to flutter app. If you need help with it just lemme know ;)

**Comment by nne998** [comment]
Hi, you can take a look at this PR:  https://github.com/abi/screenshot-to-code/pull/238

**Comment by ji4a** [comment]
I don't see it on your website: https://screenshottocode.com/
https://i.ibb.co/mJCNSwJ/Screenshot-2024-02-26-at-12-53-29.png

How can i use the flutter option?
