### ISSUE TITLE
[Suggestion] Support using Google Gemini

### ISSUE THREAD

**Issue by CynicalHeart** [abi/screenshot-to-code#215]
***Will Google Gemini be supported in the future?***

The basic version of Google Gemini also supports vision and code generation, providing an additional option to utilize this powerful project.

**Comment by rnascimento13** [comment]
plus is a lot... lot cheaper, and have a free tier

**Comment by luy98** [comment]
I tried it, and the effect was very poor, so I don’t think it makes much sense to add it, at least for now.

**Comment by CynicalHeart** [comment]
> I tried it, and the effect was very poor, so I don’t think it makes much sense to add it, at least for now.

I've tried it too and agree with you.

**Comment by Anas-Dew** [comment]
I agree. Output is poor. it is not ready yet
