### ISSUE TITLE
screenshot a URL...

### ISSUE THREAD

**Issue by lzl-hello** [abi/screenshot-to-code#216]
I can‘t screenshot a url：
![image](https://github.com/abi/screenshot-to-code/assets/96810799/3ff7ff2e-c726-4b2e-8bb0-84152e7369b4)
but the functionality to convert screenshots to code is working fine so I don't think it's a problem with my api and I don't know how to fix it

**Comment by lzl-hello** [comment]
I'm very sorry, I just saw that if you want to convert the URL code, you need to set up an additional API.

**Comment by lzl-hello** [comment]
Sorry, how can I get the api key from the screenshotone website?
is this？：
![image](https://github.com/abi/screenshot-to-code/assets/96810799/98dd1c75-7074-4814-babb-e64724df13d9)
I try it but it doesn't work

**Comment by abi** [comment]
@lzl-hello where did you put the the ScreenshotOne access key?

**Comment by lzl-hello** [comment]
> @lzl-hello where did you put the the ScreenshotOne access key?

![image](https://github.com/abi/screenshot-to-code/assets/96810799/60611c71-7b8a-4789-806a-ada0d4f28ce7)
there，

**Comment by Kepliter** [comment]
I have the same problem，Have you solved it?

**Comment by abi** [comment]
Feel free to open a new issue if you're running into issues

**Comment by lzl-hello** [comment]
> I have the same problem，Have you solved it?

It's a shame I haven't solved it yet, if you have a solution remember to kick me

**Comment by Kepliter** [comment]
> > 我也有同样的问题，你解决了吗？
> 
> 可惜我还没解决，如果你有解决办法记得踢我

This morning I pulled the latest code, restarted the project, and it works

**Comment by lzl-hello** [comment]
> > > 我也有同样的问题，你解决了吗？
> > 
> > 
> > 可惜我还没解决，如果你有解决办法记得踢我
> 
> This morning I pulled the latest code, restarted the project, and it works今天早上我拉了最新的代码，重新启动了项目，它可以工作了

Can you tell me how to fill in the Screenshot by URL Config，Is it the same as the steps I did above？

**Comment by lzl-hello** [comment]
> > > 我也有同样的问题，你解决了吗？
> > 
> > 
> > 可惜我还没解决，如果你有解决办法记得踢我
> 
> This morning I pulled the latest code, restarted the project, and it works今天早上我拉了最新的代码，重新启动了项目，它可以工作了

Surprised, it worked, but unfortunately the generation was not very satisfactory

thx

**Comment by Kepliter** [comment]
> > > > 我也有同样的问题，你解决了吗？
> > > 
> > > 
> > > 可惜我还没解决，如果你有解决办法记得踢我
> > 
> > 
> > This morning I pulled the latest code, restarted the project, and it works今天早上我拉了最新的代码，重新启动了项目，它可以工作了
> 
> Surprised, it worked, but unfortunately the generation was not very satisfactory
> 
> thx

congratulations, 
it didn’t have the desired effect, 
but it’s a good start
