### ISSUE TITLE
Facing the issue in frontend

### ISSUE THREAD

**Issue by labi1240** [abi/screenshot-to-code#22]
Error generating code. Check the Developer Console for details. Feel free to open a Github issue
Error generating code. Check the Developer Console for details. Feel free to open a Github issue

**Comment by abi** [comment]
Are you trying on the hosted website at picoapps.xyz or running locally?

**Comment by harsha-iiiv** [comment]
@abi  getting same error, but actually it is backend error.

```Error code: 404 - {'error': {'message': 'The model `gpt-4-vision-preview` does not exist or you do not have access to it. Learn more: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}```

**Comment by harsha-iiiv** [comment]
``` completion = await stream_openai_response(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/harshaam/code/screenshot-to-code/backend/llm.py", line 23, in stream_openai_response
    completion = await client.chat.completions.create(**params)
                 ^^^^^^^^^^^^^^^^^^^```

**Comment by krishhh16** [comment]
I got the same error, but It was due to me not having the backend up, hope it helps

**Comment by abi** [comment]
@harsha-iiiv you need to buy $1 of credit I think. See https://github.com/abi/screenshot-to-code#faqs

**Comment by abi** [comment]
Closing. Feel free to re-open if it's still not fixed. 

I'm not currently debugging on the hosted version (it's just a demo). Run locally if it doesn't work.
