### ISSUE TITLE
Fix false positive detection by anti-virus software such as Bitdefender

### ISSUE THREAD

**Issue by PierrunoYT** [abi/screenshot-to-code#220]
![grafik](https://github.com/abi/screenshot-to-code/assets/95778421/886ce46f-7a9c-494b-af25-c992a0ac08cf)

**Comment by Anas-Dew** [comment]
Same Issue Here.
It is happing because **clerk.screenshottocode.com** in on **URL Blacklist**.

**Comment by SolitudeSA** [comment]
I can confirm. It's being blocked by Malwarebytes too.

**Comment by abi** [comment]
Any idea how to get off this blacklist?

**Comment by SolitudeSA** [comment]
I have no idea. I ran the domain name through some blacklist checkers and they all seem fine.

**Comment by PierrunoYT** [comment]
Mhh maybe contact BitDefender to ask why it's blocked

**Comment by abi** [comment]
Yeah I will do that.

**Comment by okay-head** [comment]
I have the same issue.
Is it fixed yet?

![image](https://github.com/abi/screenshot-to-code/assets/68184623/6cd6a9d4-d11b-4572-8d18-88563f34d3a4)

**Comment by abi** [comment]
Unfortunately not. I'm not sure how to fix it. Can't you just click "I understand the risks, take me there anyway"?

**Comment by PierrunoYT** [comment]
I think it's on a Blacklist.

**Comment by abi** [comment]
I submitted a report to BitDefender and Google Safe browsing today so hopefully, it'll get taken off the blacklist shortly.

**Comment by abi** [comment]
Should be fixed now. If someone is still getting blocked by Bitdefender or their anti-virus software, please let me know. Thanks!
