### ISSUE TITLE
Session quota exceeded. Please upgrade your plan. Disabling .

### ISSUE THREAD

**Issue by salemalem** [abi/screenshot-to-code#23]
![image](https://github.com/abi/screenshot-to-code/assets/42411937/360fe315-ca67-4e77-9d8b-66f105538fc0)
![image](https://github.com/abi/screenshot-to-code/assets/42411937/eb32319d-80aa-4f90-987e-71ae8ab6fb7a)

**Comment by abi** [comment]
This is only relevant to the hosted version which includes some analytics. 

Can you try running the repo locally?
