### ISSUE TITLE
How used

### ISSUE THREAD

**Issue by mythboys** [abi/screenshot-to-code#242]
Is there a front-end page available? How should it be used?

**Comment by abi** [comment]
What are you looking to do?

**Comment by taxvui** [comment]
> Is there a front-end page available? How should it be used?

Easy to use go to https://v0.dev/
You can make code by write some thing or take screenshot of any website
Put it and press Enter you will get full source code
Some demo public
https://v0.dev/hoanghohotel
This is products of https://vercel.com
So good and free
