### ISSUE TITLE
Unable to replicate the layout.

### ISSUE THREAD

**Issue by Pattaro** [abi/screenshot-to-code#245]
Using prompt and gpt-4-version-preview, I'm unable to replicate the layout.

prompt="""
![15822033139_1 json](https://github.com/abi/screenshot-to-code/assets/39515647/4e8a04e5-c316-45bc-8826-3c232c7c9b1a)
You are an expert Tailwind developer
You take screenshots of a reference web page from the user, and then build single page apps 
using Tailwind, HTML and JS.
You might also be given a screenshot(The second image) of a web page that you have already built, and asked to
update it to look more like the reference image(The first image).

- Make sure the app looks exactly like the screenshot.
- Pay close attention to background color, text color, font size, font family, 
padding, margin, border, etc. Match the colors and sizes exactly.
- Use the exact text from the screenshot.
- Do not add comments in the code such as "" and "" in place of writing the full code. WRITE THE FULL CODE.
- Repeat elements as needed to match the screenshot. For example, if there are 15 items, the code should have 15 items. DO NOT LEAVE comments like "" or bad things will happen.
- For images, use placeholder images from https://placehold.co and include a detailed description of the image in the alt text so that an image generation AI can generate the image later.

In terms of libraries,

- Use this script to include Tailwind: <script src="https://cdn.tailwindcss.com"></script>
- You can use Google Fonts
- Font Awesome for icons: <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"></link>

Return only the full code in <html></html> tags.
Do not include markdown "```" or "```html" at the start or end.
"""

output=
![lQLPKGYppbxmQOvNBwjNC0Cwa37xu0tIC5cF0qyUlN91AA_2880_1800](https://github.com/abi/screenshot-to-code/assets/39515647/55242209-6908-4a08-8d2d-037940733c80)

**Comment by Dev-Sonal** [comment]
Helpful

**Comment by dilraj-vidyard** [comment]
write ur own code

**Comment by KolinchenkoOlha** [comment]
not bad

**Comment by abi** [comment]
<img width="905" alt="Screenshot 2024-05-23 at 5 59 08 PM" src="https://github.com/abi/screenshot-to-code/assets/23818/698d57a7-9af6-4d70-bd40-ebd31d10d9a5">

The results should be a lot better with GPT4o now.
