### ISSUE TITLE
getting error while upload the screenshot and generating the code

### ISSUE THREAD

**Issue by gangadhararaoande** [abi/screenshot-to-code#250]
Hi,
I have attached the error image below can you check and solve the issue?

<img width="1440" alt="Screenshot 2024-03-05 at 11 59 30 AM" src="https://github.com/abi/screenshot-to-code/assets/117241164/35a11d3a-1fa0-4ab1-b0ca-e712e8c106ef">

Thanks & Regards,
Gangadhara Rao Ande.

**Comment by abi** [comment]
Hi, please run the open source version or buy a subscription.  We don't offer support for the hosted version with your own API key.
