### ISSUE TITLE
what's going on? what's wrong?

### ISSUE THREAD

**Issue by leezhuuu** [abi/screenshot-to-code#253]
Excuse me, what's going on? what's wrong?

![image](https://github.com/abi/screenshot-to-code/assets/69389053/0029044b-6f61-4b22-84e8-b56d7a4d6c8f)

**Comment by abi** [comment]
Could you share your backend logs?

**Comment by leezhuuu** [comment]
I have solved this problem. I hope the author can explain in md that base url needs to add v1.
