### ISSUE TITLE
Testimonials are Overlapping in HomePage

### ISSUE THREAD

**Issue by Aman-Manwani** [abi/screenshot-to-code#256]
![image](https://github.com/abi/screenshot-to-code/assets/104587833/360732f2-db5b-4ef5-a0f2-109e3e18d4f8)
Images of testimonials are overlapping each other and also no space from the ends in the smaller screens

**Comment by abi** [comment]
Thanks for reporting this!

**Comment by Aman-Manwani** [comment]
@abi I am doing this, i will release PR soon for this issue as it is very important

**Comment by Aman-Manwani** [comment]
@abi i know it's odd but i am not able to find the file of homepage, can you please help me to locate it

**Comment by abi** [comment]
@Aman-Manwani it's in the hosted branch

**Comment by Aman-Manwani** [comment]
@abi can you review above PR and suggest changes
