### ISSUE TITLE
I have already added claud3's key, but why am I still getting MOCK data?

### ISSUE THREAD

**Issue by ArthurHsing** [abi/screenshot-to-code#260]
<img width="1126" alt="image" src="https://github.com/abi/screenshot-to-code/assets/42834985/4041c46d-a713-4229-8578-d3c2a87c13ed">
<img width="1456" alt="image" src="https://github.com/abi/screenshot-to-code/assets/42834985/0c7af6c3-59f3-4bf1-b7b5-df23328ea443">

I'm really eager to try out the features of the video generation app, but your online URL doesn't have this entry point yet, so I cloned a copy of the code locally and set the claude3 API Key in the environment variables. However, it seems to be of no use, as I'm still getting MOCK data.

**Comment by abi** [comment]
Was the issue that you had the MOCK env set? If not let me know what it is so I can fix it. 

And how do you find the video feature?
