### ISSUE TITLE
Password protected sites

### ISSUE THREAD

**Issue by ryanjAA** [abi/screenshot-to-code#262]
Was trying to test this on sites I've made with passwords, is there a way to get it to go past the login page if I log it in on the browser or a way in the UI? It just does my login page.

**Comment by abi** [comment]
No because the screenshot is taken on the server. Can you just grab the screenshot yourself? There are browser extensions that will let you grab the full page even below the fold.

**Comment by ryanjAA** [comment]
Ok - will give it a go this way (just wanted to pipe a whole bunch of stuff through we made). Much appreciated.

**Comment by abi** [comment]
@ryanjAA would love to learn more about your use case if you're open to a quick chat. You can email me at support@picoapps.xyz
