### ISSUE TITLE
May I ask if the base64 content in the transfer parameters is uploaded or updated for the first time when using prompt words to update page code

### ISSUE THREAD

**Issue by BloodyStruggle** [abi/screenshot-to-code#266]

**Comment by BloodyStruggle** [comment]
Is the update operation still based on the uploaded images, rather than the generated page images

**Comment by abi** [comment]
I'm not sure I understand your original question.

Yes, the update operation is based on the original image, unless you check this option:

<img width="356" alt="Screenshot 2024-03-14 at 4 12 01 PM" src="https://github.com/abi/screenshot-to-code/assets/23818/d6fbe891-b09d-4ee7-8bd0-b358ce8fbb5d">
