### ISSUE TITLE
Unable to access the feature

### ISSUE THREAD

**Issue by Nicoticolas** [abi/screenshot-to-code#267]
Upgraded to Tier 1 on OpenAI. I pasted the API key in setting on screenshot-to-code but it still asks me to upgrade on website. Please advise.

**Comment by c0bra** [comment]
Same. I asked some questions of their support chatbot and got this response: `Please note, we aren't currently enabling image capabilities in GPT-4.`

**Comment by abi** [comment]
Hi, you'll have to contact OpenAI support about that. I just checked and it works for me. You can use the open source version instead or buy a subscription.
