### ISSUE TITLE
Error configuring ANTHROPIC API KEY in.env file

### ISSUE THREAD

**Issue by bigfishnew** [abi/screenshot-to-code#270]
I added "ANTHROPIC_API_KEY=s****" to the.env file

"No Anthropic API key found. Please add the environment variable ANTHROPIC_API_KEY to backend/.env"

**Comment by bigfishnew** [comment]
![issue1](https://github.com/abi/screenshot-to-code/assets/103395709/3e1ed974-9b71-4979-b70e-131fb98411cc)
![issue2](https://github.com/abi/screenshot-to-code/assets/103395709/2f8acf65-9460-4b06-a9b7-7f3f37fe2996)

**Comment by abi** [comment]
@bigfishnew a couple of clarifications: is it definitely in `backend/.env` , not `frontend/.env`? In your screenshot, there's a " at the start, I'd recommend removing that.

**Comment by abi** [comment]
If you're still having problems, let me know.

**Comment by abi** [comment]
@bigfishnew can you get rid of the double quote (") at the start of your .env file?

And after we're done debugging this, please revoke this API key and use a new one so other people don't use your API key.

**Comment by bigfishnew** [comment]
![image](https://github.com/abi/screenshot-to-code/assets/103395709/5a1eadd9-e239-43b6-843d-c72b9c532892)
Without the double quotes, it still gives me an error. Another problem is that when I use Claude3, it also gives me an error if I don't set the OpenAI API Key in the Settings
![image](https://github.com/abi/screenshot-to-code/assets/103395709/51537ea5-a67d-4c78-af41-43ac54983baa)

**Comment by abi** [comment]
@bigfishnew thanks for bringing the bug "when I use Claude3, it also gives me an error if I don't set the OpenAI API Key in the Settings" to my attention. I just fixed it.

Unfortunately, I'm not able to replicate your issue with the .env file. It works for me. Can you try directly modifying the code here: https://github.com/abi/screenshot-to-code/blob/7f44228a9582f6e39e8dbcee7598b86328ef7e74/backend/config.py#L6 and let me know if that fixes it?

**Comment by bigfishnew** [comment]
Just replace "ANTHROPIC_API_KEY" in the configuration file and there will be no error. But the console will raise an Error like this,"PermissionDeniedError: Error code: 403 - {'error': {'type': 'forbidden', 'message': 'Request not allowed'}}" I don't know if it has anything to do with me being in China. I don't know how to configure the agent in this software

**Comment by abi** [comment]
Yeah, I don't see China on this list: https://www.anthropic.com/supported-countries 

You could try a VPN or proxy. I also just released Claude support to the paid version here: https://screenshottocode.com
