### ISSUE TITLE
I'm using GPT4 and OPENAI_API_KEY is configured. The Anthropic API key is not found. What should I do?

### ISSUE THREAD

**Issue by xiaohaohao24** [abi/screenshot-to-code#275]
![WX20240320-002527](https://github.com/abi/screenshot-to-code/assets/149742670/a7ebba02-af61-4352-b19f-b6e93c10b02c)
![WX20240320-002658](https://github.com/abi/screenshot-to-code/assets/149742670/2acc918d-d39c-4444-9553-a5e03c9471c4)

**Comment by abi** [comment]
Sorry this is confusing. Looks like you recorded a video. Videos only work with the Anthropic models. GPT-4 vision sucks at videos.

I updated the pop-up message to be clearer. You can see instructions here: https://github.com/abi/screenshot-to-code/blob/main/blog/video-to-app.md

Thanks for highlighting this! Closing issue for now. Feel free to re-open if it's still not working after you get an Anthropic API key.
