### ISSUE TITLE
How to connect with Azure OPENAI Service?

### ISSUE THREAD

**Issue by jme418** [abi/screenshot-to-code#276]
Hello guys!

I'm just wondering if it's already possible to connect Azure OPEN AI Service in any way to use the screenshot-to-code function or this is not being supported and won't in a while.

I can see there is PR created to add azure support but I don't think is available yet. Am I wrong?

Thanks!

**Comment by abi** [comment]
@jme418 See #10 We haven't added support for this yet but hopefully soon. You can check out the PR and use that branch for now.

**Comment by jme418** [comment]
The branch you refer to is .../cristianorevil/screenshot-to-code/tree/azure-support, right? Or is there another one?

**Comment by abi** [comment]
Yup, that one!

**Comment by ychyjj** [comment]
> @jme418 See #10 We haven't added support for this yet but hopefully soon. You can check out the PR and use that branch for now.
Great, I hope to integrate with Azure as soon as possible because for some reasons, I can only use Azure's API.

**Comment by jme418** [comment]
I know, the problem is that I don't know why that branch is not working for me neither. I guess I'm missing something.

Thanks for answering!
________________________________

**Comment by abi** [comment]
@jme418 try giving Claude a try if you can get access to Anthropic?

**Comment by jme418** [comment]
The thing is that I can't afford paying for the service and I have a coupon on Azure so that's why I'm interested in that payment method (Azure credit).
________________________________

**Comment by abi** [comment]
Gotcha! Hope to support Azure soon in this repo. And also local models once they get good (they are pretty bad at the moment).

**Comment by ashsmith88** [comment]
Firstly - great module @abi 
I have just forked this and got the current version working with AzureOpenAI - it was relatively simple and could create a PR if people are interested still @jme418
