### ISSUE TITLE
Docker compose don't recognize it 

### ISSUE THREAD

**Issue by Test67766** [abi/screenshot-to-code#279]
PS C:\Users\**********\Downloads\screenshot-to-code-main> echo "OPENAI_API_KEY=sk-WBO2ygSa4o3****" > .env                                                                                                     PS C:\Users\**********\Downloads\screenshot-to-code-main> docker-compose up -d --build       
                         
failed to read C:\Users\**********\Downloads\screenshot-to-code-main\.env: line 1: unexpected character "�" in variable name "\xff\xfeO\x00P\x00E\x00N\x00A\x00I\x00_\x00A\x00P\x00I\x00_\x00K\x00E\x00Y\x00=\x00s\x00k\x00-\x00W\x00B\********

**Comment by Test67766** [comment]
The same issue on Linux

**Comment by abi** [comment]
This might fix your issue: https://github.com/abi/screenshot-to-code/issues/161
