### ISSUE TITLE
Unable to run it despite upgrading to GPT4. Need assistance. 

### ISSUE THREAD

**Issue by yashk1998** [abi/screenshot-to-code#282]
![image](https://github.com/abi/screenshot-to-code/assets/33251900/8824da5d-5f8c-45a1-8075-2057b6326d33)

My Limits Page photo: 
![image](https://github.com/abi/screenshot-to-code/assets/33251900/1f47647f-1887-4c36-8c43-371be110f83c)

**Comment by abi** [comment]
Please reach out to OpenAI support. I can't really help here.

**Comment by RichardLeeHuang** [comment]
@yashk1998 Issue is closed but just chiming in here. I ran into this same issue because I didn't add credits to my account despite upgrading to GPT4. You need to add credits to your account AND set it to renew when credits run out in order to be upgraded to Tier 1.

**Comment by yashk1998** [comment]
Thanks!

**Comment by abi** [comment]
@RichardLeeHuang thanks for the tip! I added it to https://github.com/abi/screenshot-to-code/blob/main/Troubleshooting.md
