### ISSUE TITLE
Error while configurating to use Azure OPEN AI Service

### ISSUE THREAD

**Issue by jme418** [abi/screenshot-to-code#283]
Hi there! I'm trying to use Azure OPEN AI Service following steps in https://github.com/cristianorevil/screenshot-to-code/tree/azure-support but an error is happening to me.

I'll show all I've done step by step:

1.
![image](https://github.com/abi/screenshot-to-code/assets/90529450/1537b02a-0e13-4fc4-9bfa-d10a0f0431f6)

2.
![image](https://github.com/abi/screenshot-to-code/assets/90529450/20f46a64-1728-453a-a2ea-460d1134b59a)
(Not sure about AZURE_OPENAI_API_VERSION & AZURE_OPENAI_DALLE3_API_VERSION values, I've tried setting AZURE_OPENAI_API_VERSION=vision-preview and AZURE_OPENAI_DALLE3_API_VERSION=3.0 which are the model versions but it is not working neither)

3. Command "pip install poetry" (no warnings or anything indicating an error).
![image](https://github.com/abi/screenshot-to-code/assets/90529450/fbe0934e-96a1-48dd-958f-79f383d17fa3)

4.
![image](https://github.com/abi/screenshot-to-code/assets/90529450/bf3f3128-2d5b-443c-877e-744a0e322116)

5.
![image](https://github.com/abi/screenshot-to-code/assets/90529450/4473e639-31fa-41f2-b5ec-9312d8dc2afb)

6. Command "yarn dev".
![image](https://github.com/abi/screenshot-to-code/assets/90529450/69bfe044-e57b-4bf4-9927-06080922c1be)

ERROR:
![image](https://github.com/abi/screenshot-to-code/assets/90529450/544ffd14-b496-409e-81cc-d9996d5a549e)

Can't see any error log information anywhere.

That's all, thanks for reading!

**Comment by hoanghohotel** [comment]
https://v0.dev/
It free from https://vercel.com/

**Comment by abi** [comment]
Merging with #10
