### ISSUE TITLE
windows defender detects virus with code from screenshottocode??? is this false positivte?

### ISSUE THREAD

**Issue by ahmedomar365** [abi/screenshot-to-code#287]
![image](https://github.com/abi/screenshot-to-code/assets/70892817/ba5e2ff2-70dd-4853-8581-815bf48ab193)

**Comment by ahmedomar365** [comment]
it says trojan

**Comment by abi** [comment]
Yeah that's strange. Looks like your previous generation did not trigger it.

If you're concerned, I'd recommend, just doing another generation.

**Comment by ahmedomar365** [comment]
I need this generation the thing is I paid 0.30 for it lol, the prev one was without dale 🥲🥲🥲🥲I only need this

**Comment by ahmedomar365** [comment]
> Yeah that's strange. Looks like your previous generation did not trigger it.
> 
> If you're concerned, I'd recommend, just doing another generation.

sad 
![image](https://github.com/abi/screenshot-to-code/assets/70892817/d95e520a-a4bf-4864-b765-7c5c0f46a473)
there goes 0.30 🥲

**Comment by abi** [comment]
Feel free to inspect the code and decide if there's anything wrong with it. I'm very doubtful that OpenAI is going to respond with trojan code.
