### ISSUE TITLE
Error generating code. Check the Developer Console AND the backend logs for details. Feel free to open a Github issue.

### ISSUE THREAD

**Issue by ANASPINOZA** [abi/screenshot-to-code#288]
<img width="720" alt="Screenshot 2024-03-26 102630" src="https://github.com/abi/screenshot-to-code/assets/94518801/550beb6d-d52a-4cdc-b26e-9bb9b1215ae2">

**Comment by ANASPINOZA** [comment]
in this pic is the back-end logs , what is happening

**Comment by abi** [comment]
Please see README faq section for utf8 solution.

**Comment by penelope1234564867** [comment]
I meet this promblem too？ how can I sove it？
