### ISSUE TITLE
why result code is empty 

### ISSUE THREAD

**Issue by freshgeek** [abi/screenshot-to-code#299]
why result code is empty  

the front websocket result ： {"type":"setCode","value":""} 

and py ： 
 completion = await stream_openai_response

completion  is empty

**Comment by abi** [comment]
Hi, we'll need more information to debug this.

- Can you share your backend logs?
- Does this happen for one image or all images?

**Comment by freshgeek** [comment]
thanks,  this is logs file and image demo 
[messages_20240408_171908.json](https://github.com/abi/screenshot-to-code/files/14925601/messages_20240408_171908.json)

![01 - 2](https://github.com/abi/screenshot-to-code/assets/20513615/aa56f92d-134d-41fb-a57a-8b92303de1e2)

**Comment by it-tin** [comment]
I also encountered the same problem as you, I used a proxy address.
If you are using a proxy address, try adding '/v1' after the address, for example: https://www.xxxxx.xxx/v1

**Comment by abi** [comment]
@freshgeek I'm looking for logs from the Python backend server to help you fix the problem.

**Comment by Srpihot** [comment]
same problem, I used a proxy address too,result code is empty.

**Comment by abi** [comment]
@Srpihot logs would be helpful to debug.

**Comment by freshgeek** [comment]
> I also encountered the same problem as you, I used a proxy address. If you are using a proxy address, try adding '/v1' after the address, for example: https://www.xxxxx.xxx/v1
this is useful for me 。
