### ISSUE TITLE
why result code is empty？

### ISSUE THREAD

**Issue by it-tin** [abi/screenshot-to-code#300]
why result code is empty

the front websocket result ： {"type":"status","value":"Code generation complete."}
![image](https://github.com/abi/screenshot-to-code/assets/65693158/68cc48ef-7928-4791-889a-b2dfed6bc8f4)

and llm.py ：
stream = await client.chat.completions.create(**params)
[messages_20240409_142906.json](https://github.com/abi/screenshot-to-code/files/14914253/messages_20240409_142906.json)

![image](https://github.com/abi/screenshot-to-code/assets/65693158/23625f02-13ad-4cfa-939a-2006117627f8)

All the pictures are like this，completion is empty，I am using a proxy URL

**Comment by it-tin** [comment]
Solved, we need to add v1 after the proxy URL, for example: https://xxx.xxxxx.xxx/v1

**Comment by tianerphil** [comment]
I am running on localhost with docker. I have the same issue, it seems from the log, some code is generated, while from the UI which is http://localhost:5173/ nothing shows up. what do you mean by "we need to add v1 after the proxy URL, for example: https://xxx.xxxxx.xxx/v1" do you mean I should access from http://localhost:5173/v1 ? thx

**Comment by tianerphil** [comment]
![Uploading Screenshot 2024-06-22 at 11.52.44.png…]()

**Comment by abi** [comment]
@tianerphil your logs image upload didn't seem to work. Can you share your backend and front-end logs? Please open a new issue so I can help you out.

The proxy is for the connection to OpenAI, not for this backend. The proxy URL needs to be specified in the front-end settings. 
<img width="505" alt="Screenshot 2024-06-23 at 5 46 17 PM" src="https://github.com/abi/screenshot-to-code/assets/23818/3ef7bd05-1a2f-4c89-9ae0-01c6a71ea7fc">

**Comment by tianerphil** [comment]
Hi Abi,


thank you for your prompt response. I have created the new issue #366 with all the necessory logs and screenshot. please kindly check when you are free.
have a nice day today.
https://github.com/abi/screenshot-to-code/issues/366#issue-2368500422



Best Regards,
Liang Zhang
0509119456









                       
Original
                       
                     

From:"Abi Raja"< ***@***.*** &gt;;

Date:2024/6/23 13:47

To:"abi/screenshot-to-code"< ***@***.*** &gt;;

CC:"Liang.Zhang"< ***@***.*** &gt;;"Mention"< ***@***.*** &gt;;

Subject:Re: [abi/screenshot-to-code] why result code is empty？ (Issue #300)




 
@tianerphil your logs image upload didn't seem to work. Can you share your backend and front-end logs? Please open a new issue so I can help you out.
 
The proxy is for the connection to OpenAI, not for this backend. The proxy URL needs to be specified in the front-end settings.
 Screenshot.2024-06-23.at.5.46.17.PM.png (view on web)

**Comment by tianerphil** [comment]
Hi Abi,&nbsp;


just gentle reminder if you have time please kindly check around the newly created issue 366, which i believe is not a major one, could be fixed easily. thank you so much.


Best Regards,
Liang Zhang
0509119456









                       
Original
                       
                     

From:"phil阿良"< ***@***.*** &gt;;

Date:2024/6/23 14:58

To:"abi/screenshot-to-code"< ***@***.*** &gt;;

Subject:Re:Re: [abi/screenshot-to-code] why result code is empty？ (Issue #300)


Hi Abi,


thank you for your prompt response. I have created the new issue #366 with all the necessory logs and screenshot. please kindly check when you are free.
have a nice day today.
https://github.com/abi/screenshot-to-code/issues/366#issue-2368500422



Best Regards,
Liang Zhang
0509119456









                       
Original
                       
                     

From:"Abi Raja"< ***@***.*** &gt;;

Date:2024/6/23 13:47

To:"abi/screenshot-to-code"< ***@***.*** &gt;;

CC:"Liang.Zhang"< ***@***.*** &gt;;"Mention"< ***@***.*** &gt;;

Subject:Re: [abi/screenshot-to-code] why result code is empty？ (Issue #300)




 
@tianerphil your logs image upload didn't seem to work. Can you share your backend and front-end logs? Please open a new issue so I can help you out.
 
The proxy is for the connection to OpenAI, not for this backend. The proxy URL needs to be specified in the front-end settings.
 Screenshot.2024-06-23.at.5.46.17.PM.png (view on web)
