### ISSUE TITLE
Error generating code on screenshottocode.com

### ISSUE THREAD

**Issue by kevin700523** [abi/screenshot-to-code#302]
Error generating code. 
Check the Developer Console AND the backend logs for details. 
Feel free to open a Github issue.

**Comment by abi** [comment]
How are you using screenshottocode.com? We only provide on the hosted version if you're a paying customer.

**Comment by kevin700523** [comment]
i was using GPT-4 and all was ok to generate code. But since two days ago, the site shows this message "Error generating code. Check the Developer Console AND the backend logs for details. Feel free to open a Github issue."

**Comment by abi** [comment]
As I mentioned, we don't provide support for the hosted version due to lack of logs. Please use the open source version locally or sign up for a paid plan on the hosted version.
