### ISSUE TITLE
Error generating code.Check the Developer Console AND the backend logs for details.Feel free to open a Github issue.

### ISSUE THREAD

**Issue by wshwhyu** [abi/screenshot-to-code#305]
![16e0b628ee2b5f7d02002447680ad81](https://github.com/abi/screenshot-to-code/assets/16811625/76aebc1d-f9ed-4c84-a789-d386fe55ede6)

**Comment by wshwhyu** [comment]
![image](https://github.com/abi/screenshot-to-code/assets/16811625/405df8de-2b6b-4f72-bd8e-f85457c790f2)

**Comment by wshwhyu** [comment]
The information on the backend and the frontend are screenshotted, please help me see where the problem is, thank you

**Comment by wshwhyu** [comment]
This problem is solved because the API key is not filled in the front-end settings

**Comment by abi** [comment]
Great.
