### ISSUE TITLE
Your backend is running correctly. Please open the front-end URL (default is http://localhost:5173) to use screenshot-to-code.

### ISSUE THREAD

**Issue by lbnlsj** [abi/screenshot-to-code#315]
My application running without error, but I can't open the front-end URL (http://localhost:5173) which remind me ERR_CONNECTION_REFUSED, but the other url can be visit. Thank you!
![image](https://github.com/abi/screenshot-to-code/assets/58318195/7fb94d07-1d83-418a-922d-708a5b00a5cf)
![image](https://github.com/abi/screenshot-to-code/assets/58318195/22977179-2a32-4993-bbb4-765ff2ff72b0)
![image](https://github.com/abi/screenshot-to-code/assets/58318195/c2ce5488-0b19-460c-9077-5bd0e9465ddc)

**Comment by abi** [comment]
Can you try 127.0.0.1:5173?

**Comment by yellow1912** [comment]
I'm having the same issue. I run the app from WSL environment. The backend works but the frontend does not show anything (exact same error).

**Comment by abi** [comment]
Are you running your front end? It needs to be run separately from your backend.

**Comment by yellow1912** [comment]
@abi you are right, I need to run frontend as well. The document structure makes it look like the part regarding frontend code part of the Anthropic section right above it and I was confused.

**Comment by abi** [comment]
Thanks for the feedback. I'll update the docs.
