### ISSUE TITLE
Error code 139, Segmentation fault

### ISSUE THREAD

**Issue by MarcusLeoTKM** [abi/screenshot-to-code#316]
<img width="699" alt="Screenshot 2024-04-30 at 4 22 42 PM" src="https://github.com/abi/screenshot-to-code/assets/144979427/94ad6ba8-f7ab-42f6-bbce-c9881dc54783">

When I set up the .env file, and run `docker compose up` in the project root directory, the backend is being built, but the fronted doesn't seem to work. I suspect this is because of the version of node in `/frontend/Dockerfile`. Because right after I changed the node version from `FROM node:20.9-bullseye-slim` to `FROM node:22-bullseye-slim`, the frontend website started to show.

**Comment by abi** [comment]
Awesome, thanks for debugging and opening the PR. Will merge it shortly.
