### ISSUE TITLE
`gpt-4o-2024-05-13` does not exist 

### ISSUE THREAD

**Issue by SongOnWater** [abi/screenshot-to-code#332]
I can't finish the process and got the error message :
[GENERATE_CODE] Model not found Error code: 404 - {'error': {'message': 'The model `gpt-4o-2024-05-13` does not exist or you do not have access to it.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}
Is there any method to solve this issue.

**Comment by abi** [comment]
Have you followed the instructions in the README to deposit $5 to get gpt 4 access?

**Comment by naman1608** [comment]
@abi Hi, I have explored the screenshot to code in detail since some time and wish to contribute, is there any issue or feature which I can work upon? Thanks

**Comment by abi** [comment]
Thanks, @naman1608 feel free to pick up any of the open issues.
