### ISSUE TITLE
Handle Nones in chunk.choices[0].delta

### ISSUE THREAD

**Issue by laolin5564** [abi/screenshot-to-code#336]
![WechatIMG434](https://github.com/abi/screenshot-to-code/assets/158557918/d2ddcd3e-f944-40cb-a74e-b54bec8938f4)

There is a successful request for the openai interface, but it seems that no code is generated.

backend-1   | ERROR:    Exception in ASGI application
backend-1   | Traceback (most recent call last):
backend-1   |   File "/usr/local/lib/python3.12/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 250, in run_asgi
backend-1   |     result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
backend-1   |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-1   |   File "/usr/local/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
backend-1   |     return await self.app(scope, receive, send)
backend-1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-1   |   File "/usr/local/lib/python3.12/site-packages/fastapi/applications.py", line 276, in __call__
backend-1   |     await super().__call__(scope, receive, send)
backend-1   |   File "/usr/local/lib/python3.12/site-packages/starlette/applications.py", line 122, in __call__
backend-1   |     await self.middleware_stack(scope, receive, send)
backend-1   |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 149, in __call__
backend-1   |     await self.app(scope, receive, send)
backend-1   |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/cors.py", line 75, in __call__
backend-1   |     await self.app(scope, receive, send)
backend-1   |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
backend-1   |     raise exc
backend-1   |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
backend-1   |     await self.app(scope, receive, sender)
backend-1   |   File "/usr/local/lib/python3.12/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
backend-1   |     raise e
backend-1   |   File "/usr/local/lib/python3.12/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
backend-1   |     await self.app(scope, receive, send)
backend-1   |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 718, in __call__
backend-1   |     await route.handle(scope, receive, send)
backend-1   |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 341, in handle
backend-1   |     await self.app(scope, receive, send)
backend-1   |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 82, in app
backend-1   |     await func(session)
backend-1   |   File "/usr/local/lib/python3.12/site-packages/fastapi/routing.py", line 289, in app
backend-1   |     await dependant.call(**values)
backend-1   |   File "/app/routes/generate_code.py", line 251, in stream_code
backend-1   |     completion = await stream_openai_response(
backend-1   |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-1   |   File "/app/llm.py", line 62, in stream_openai_response
backend-1   |     content = chunk.choices[0].delta.content or ""
backend-1   |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-1   | AttributeError: 'NoneType' object has no attribute 'content'
backend-1   | INFO:     connection closed

**Comment by abi** [comment]
That is strange and I haven't seen that before. Are you able to access OpenAI in your country? And with other apps?

**Comment by abi** [comment]
I would try printing chunk.choices here to see what the response looks like:

backend-1 | File "/app/llm.py", line 62, in stream_openai_response
backend-1 | content = chunk.choices[0].delta.content or ""
backend-1 | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by laolin5564** [comment]
I don't quite understand, do I need to modify the code?

> 我将尝试在这里打印 chunk.choices 来查看响应是什么样子的：
> 
> 后端-1 |文件“/app/llm.py”，第 62 行，在stream_openai_response backend-1 | content = chunk.choices[0].delta.content 或 "" backend-1 | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by kenny-it** [comment]
I change this line
`content = chunk.choices[0].delta.content or ""`
to 
`content = "" if chunk.choices[0].delta is None else chunk.choices[0].delta.content or ""`

this work for me.

**Comment by abi** [comment]
Awesome, thanks for sharing. I'll update the code to fix this problem.
