### ISSUE TITLE
Heeeelp! can not run

### ISSUE THREAD

**Issue by nzd520** [abi/screenshot-to-code#34]
Heeeelp! I ran it locally, but on the website, "Error generating code. Check the Developer Console for details. Feel free to open a Github issue." The project can run on both the front and back ends, but when the back end runs, a message "The current project could not be installed: No file/folder found for package backend If you do not want to install the current project use --no-root ", I do not know whether it is relevant

**Comment by nzd520** [comment]
when i push F12, the source  on web said
"
Download the React DevTools for a better development experience: https://reactjs.org/link/react-devtools
generateCode.ts? [sm]:23 Connecting to backend @  ws://127.0.0.1:7000/generate-code
generateCode.ts? [sm]:25 WebSocket connection to 'ws://127.0.0.1:7000/generate-code' failed: 
generateCode @ generateCode.ts? [sm]:25
generateCode.ts? [sm]:56 WebSocket error Event
(anonymous) @ generateCode.ts? [sm]:56
generateCode.ts? [sm]:46 Connection closed 1006 
generateCode.ts? [sm]:48 WebSocket error code CloseEvent
(anonymous) @ generateCode.ts? [sm]:48
"

**Comment by abi** [comment]
Would you look at the link in the README section? That should solve your problem.

**Comment by nzd520** [comment]
it dont work! TT .Create an OpenAI account. And then, you need to buy at least $1 worth of credit on the [Billing dashboard](https://platform.openai.com/account/billing/overview). i do it, but it still said 
"Error generating code. Check the Developer Console for details. Feel free to open a Github issue
Error generating code. Check the Developer Console for details. Feel free to open a Github issue"
how can i do!!!TT

**Comment by abi** [comment]
Could you paste your backend logs? That should be helpful in understanding the issue.

**Comment by nickcartery** [comment]
> Could you paste your backend logs? That should be helpful in understanding the issue.
We're using your demo site with our ChatGPT-4 API key: https://picoapps.xyz/free-tools/screenshot-to-code

**Comment by nzd520** [comment]
backend logs:
"
>> poetry install
>> poetry shell
>> poetry run uvicorn main:app --reload --port 7000
Installing dependencies from lock file


Installing the current project: backend (0.1.0)
The current project could not be installed: No file/folder found for package backend
If you do not want to install the current project use --no-root
Spawning shell within C:\Users\小小峰\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Local\pypoetry\Cache\virtualenvs\backend-mf7PE-pK-py3.10
Windows PowerShell
版权所有 (C) Microsoft Corporation。保留所有权利。

尝试新的跨平台 PowerShell https://aka.ms/pscore6
"
I runit on VSCode

**Comment by nzd520** [comment]
in frontend factory, the @tailwind in 'index.css' said Unknown at rule @tailwindcss(unknownAtRules) ,is that problem?

**Comment by abi** [comment]
@nzd520 have you tried this? https://github.com/abi/screenshot-to-code/issues/3#issuecomment-1814777959

**Comment by abi** [comment]
@nickcartery not offering support for hosted version at the moment. Please run locally.

**Comment by nzd520** [comment]
i try it, but still can`t work , on the website console, it said 
"
Download the React DevTools for a better development experience: https://reactjs.org/link/react-devtools
generateCode.ts? [sm]:23 Connecting to backend @  ws://127.0.0.1:7001/generate-code
generateCode.ts? [sm]:25 WebSocket connection to 'ws://127.0.0.1:7001/generate-code' failed: 
generateCode @ generateCode.ts? [sm]:25
doGenerateCode @ App.tsx? [sm]:72
doCreate @ App.tsx? [sm]:85
(anonymous) @ ImageUpload.tsx? [sm]:80
generateCode.ts? [sm]:56 WebSocket error Event {isTrusted: true, type: 'error', target: WebSocket, currentTarget: WebSocket, eventPhase: 2, …}
(anonymous) @ generateCode.ts? [sm]:56
error (async)
generateCode @ generateCode.ts? [sm]:55
doGenerateCode @ App.tsx? [sm]:72
doCreate @ App.tsx? [sm]:85
(anonymous) @ ImageUpload.tsx? [sm]:80
Promise.then (async)
onDrop @ ImageUpload.tsx? [sm]:79
(anonymous) @ index.js:708
(anonymous) @ index.js:759
Promise.then (async)
(anonymous) @ index.js:758
(anonymous) @ index.js:831
(anonymous) @ index.js:192
(anonymous) @ index.js:190
callCallback2 @ react-dom.development.js:4164
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:4291
executeDispatch @ react-dom.development.js:9041
processDispatchQueueItemsInOrder @ react-dom.development.js:9073
processDispatchQueue @ react-dom.development.js:9086
dispatchEventsForPlugins @ react-dom.development.js:9097
(anonymous) @ react-dom.development.js:9288
batchedUpdates$1 @ react-dom.development.js:26140
batchedUpdates @ react-dom.development.js:3991
dispatchEventForPluginEventSystem @ react-dom.development.js:9287
dispatchEventWithEnableCapturePhaseSelectiveHydrationWithoutDiscreteEventReplay @ react-dom.development.js:6465
dispatchEvent @ react-dom.development.js:6457
dispatchDiscreteEvent @ react-dom.development.js:6430
Show 21 more frames
generateCode.ts? [sm]:46 Connection closed 1006 
generateCode.ts? [sm]:48 WebSocket error code CloseEvent {isTrusted: true, wasClean: false, code: 1006, reason: '', type: 'close', …}isTrusted: truebubbles: falsecancelBubble: falsecancelable: falsecode: 1006composed: falsecurrentTarget: WebSocket {url: 'ws://127.0.0.1:7001/generate-code', readyState: 3, bufferedAmount: 0, onopen: null, onerror: null, …}defaultPrevented: falseeventPhase: 0reason: ""returnValue: truesrcElement: WebSocket {url: 'ws://127.0.0.1:7001/generate-code', readyState: 3, bufferedAmount: 0, onopen: null, onerror: null, …}target: WebSocket {url: 'ws://127.0.0.1:7001/generate-code', readyState: 3, bufferedAmount: 0, onopen: null, onerror: null, …}timeStamp: 10828type: "close"wasClean: false[[Prototype]]: CloseEvent
(anonymous) @ generateCode.ts? [sm]:48
"

is that problem? plz TT i really want to try this

**Comment by abi** [comment]
@nzd520 can you share backend logs again? front-end logs are not very helpful, all they say is that the generate code endpoint is failing.

**Comment by nzd520** [comment]
now i run the backend code, sometimes it said 
"
>> poetry install
>> poetry shell
>> poetry run uvicorn main:app --reload --port 7000
Installing dependencies from lock file

No dependencies to install or update

Installing the current project: backend (0.1.0)
Virtual environment already activated: C:\Users\小小峰\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Local\pypoetry\Cache\virtualenvs\backend-yc4DYrCP-py3.10
INFO:     Will watch for changes in these directories: ['C:\\Users\\小小峰\\Desktop\\大二下文档\\python-project\\screenshot-to-code-main\\backend']
INFO:     Uvicorn running on http://127.0.0.1:7000 (Press CTRL+C to quit)
INFO:     Started reloader process [25820] using StatReload
ERROR:    Error loading ASGI app. Could not import module "main".
"
and i run the common #3 said:
"cd backend
mkdir backend # yes, inside backend
mv *.py backend/
poetry install
poetry shell
cd backend # yes, backend/backend
poetry run uvicorn main:app --reload --port 7000
"
sometimes it can run, like that:
"
>> poetry install
>> poetry shell
>> poetry run uvicorn main:app --reload --port 7000
Installing dependencies from lock file

No dependencies to install or update

Installing the current project: backend (0.1.0)
Spawning shell within C:\Users\小小峰\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Local\pypoetry\Cache\virtualenvs\backend-yc4DYrCP-py3.10
Windows PowerShell
版权所有 (C) Microsoft Corporation。保留所有权利。

尝试新的跨平台 PowerShell https://aka.ms/pscore6
"

Do you understand what I'm saying? Thank you very much!

**Comment by abi** [comment]
@FuZZingB your front end should be running at http://127.0.0.1:5173 not :7001

**Comment by abi** [comment]
@FuZZingB And what happens you load that page in the browser?

**Comment by NgXuanKhoa** [comment]
> @FuZZingB And what happens you load that page in the browser?

![image](https://github.com/abi/screenshot-to-code/assets/120007712/28b80e6c-b7d6-4869-b401-c82af7efef1f)

**Comment by abi** [comment]
@NgXuanKhoa pretty sure you are going to http://127.0.0.1:7001 rather than front-end.

**Comment by abi** [comment]
Closing this because there's too many people talking about too many different issues. Please open new separate issues if you need help.
