### ISSUE TITLE
Error generating code. Check the Developer Console AND the backend logs for details. Feel free to open a Github issue.

### ISSUE THREAD

**Issue by anasMARZAK** [abi/screenshot-to-code#340]
hey, 
i'v downlowded the source code from github of this project , i do all the steps to setup the project and whene i try to lanch it i see this warning msg 
![Screenshot 2024-05-23 154501](https://github.com/abi/screenshot-to-code/assets/76627567/9b2ef2b5-4080-485f-97af-cc4a7c14746f)
 i have chatgbt 4o token so i think its not the problem so pls help

**Comment by anasMARZAK** [comment]
umm , i fixed it its want just to change .env file decoding to "UTF-8", but i get some problems i think i want get credit to use the api corectly right? if yes is 1$ enough?
![Screenshot 2024-05-23 174839](https://github.com/abi/screenshot-to-code/assets/76627567/973b3c03-b002-46f4-ad98-135db291dcd0)

**Comment by abi** [comment]
Please see the README for details.
