### ISSUE TITLE
Error generating code. 

### ISSUE THREAD

**Issue by rectinajh** [abi/screenshot-to-code#347]
**Describe the bug**
deploy on ubuntu.
Error generating code. Check the Developer Console AND the backend logs for details. Feel free to open a Github issue.

<img width="1180" alt="image" src="https://github.com/abi/screenshot-to-code/assets/3462559/31049179-9ee5-4f91-8406-d01262503804">

**Comment by abi** [comment]
Please share your logs and reopen the issue.
