### ISSUE TITLE
Error code: 404 - {'error': {'message': 'The model `gpt-4o-2024-05-13` does not exist or you do not have access to it.', 'type': 'invalid_request_error', 'param':

### ISSUE THREAD

**Issue by megaultraprohacker** [abi/screenshot-to-code#365]
Please help

![image](https://github.com/abi/screenshot-to-code/assets/154434118/d42156c8-5315-4da6-a8f4-c1dfcf25c2a2)

**Comment by megaultraprohacker** [comment]
its local

**Comment by abi** [comment]
Have you followed the steps here? https://github.com/abi/screenshot-to-code/blob/main/Troubleshooting.md Your account might not have access to GPT4o

**Comment by megaultraprohacker** [comment]
my account has no 5$. is there anyone who sells cheap apis? please i really need to this.

**Comment by abi** [comment]
I'm not aware of anywhere where it would be cheaper than $5. I'd recommend just using free ChatGPT instead of screenshot to code.
