### ISSUE TITLE
There appears to be trouble with your network connection. Retrying...

### ISSUE THREAD

**Issue by Zenefff** [abi/screenshot-to-code#371]
During step 5 I get this message and cannot continue the docker-compose build:

**There appears to be trouble with your network connection. Retrying...**

![image](https://github.com/abi/screenshot-to-code/assets/128839028/40940caf-1566-4515-b13d-b3fb7a329f26)

Any ideas how to resolve this?
Internet connection is wired and working fine.

**Comment by abi** [comment]
I'm not sure. I haven't seen this issue before. Could you start afresh and try again?

**Comment by Zenefff** [comment]
Tried after few restarts but did not help.
Managed to get it working after fresh linux install.
