### ISSUE TITLE
code is not getting generated on Mac OS Catalina

### ISSUE THREAD

**Issue by diablodeveloper** [abi/screenshot-to-code#374]
**Describe the bug**
I pulled down the code, followed the steps to install. Front end is running but not generating any html code nor anything in the terminal in terms of logs. Help here would be appreciated.

**To Reproduce**
1. Run backend
2. Run frontend
3. navigate to localhost url
4. Drag and drop a screenshot
5. Spinners running but nothing generates
6. Error shown on screen that unable to generated code, plz check logs
7. but no logs are getting generated
8. When I navigate to 127.x.x.x url, nothing shows as if backend is not connecting to front end  maybe?

**Screenshots of backend AND frontend terminal logs**
Below screenshots of terminal windows showing frontend and backend:

<img width="864" alt="Screen Shot 2024-07-10 at 9 19 59 AM" src="https://github.com/abi/screenshot-to-code/assets/2354826/bbfd951f-4b54-4022-a248-4a569db0c6aa">
<img width="564" alt="Screen Shot 2024-07-10 at 9 20 15 AM" src="https://github.com/abi/screenshot-to-code/assets/2354826/61451371-a11f-4630-aac6-a497fb0e0673">

**Comment by diablodeveloper** [comment]
Was able to resolve the issue by fixing the pydantic version in the docker file.

**Comment by abi** [comment]
Awesome, we've got to fix the pydantic version issue in the main repo. Thanks for sharing the solution!

**Comment by diablodeveloper** [comment]
@abi Alternately, add an additional instruction to fix pydantic version before running backend
