### ISSUE TITLE
User Error generating code. Check the Developer Console AND the backend logs for details. Feel free to open a Github issue

### ISSUE THREAD

**Issue by Belka-kate** [abi/screenshot-to-code#376]
<img width="1440" alt="Снимок экрана 2024-07-16 в 18 47 45" src="https://github.com/user-attachments/assets/df76641c-71d6-4711-9da0-1cc2e813f5c8">
<img width="1440" alt="Снимок экрана 2024-07-16 в 18 49 38" src="https://github.com/user-attachments/assets/872218b9-5185-4e69-9dbb-c493848da7ff">
<img width="1440" alt="Снимок экрана 2024-07-16 в 18 51 59" src="https://github.com/user-attachments/assets/80ebdf7f-961f-4b3e-a694-b4b156a24f71">

Hello. I'm trying to upload something but it writes "User Error generating code. Check the Developer Console AND the backend logs for details. Feel free to open a Github issue". I attach screenshots of console (maybe it will help but not sure) and some more, but I don't know how to open backend logs (I'm running from Mac version 12.0.1  if it is important). Please help to do something with that, thank you

**Comment by abi** [comment]
You need to run your backend with poetry run uvicorn main:app --reload --port 7001 in a separate console tab

**Comment by Belka-kate** [comment]
<img width="1440" alt="Снимок экрана 2024-07-16 в 22 21 40" src="https://github.com/user-attachments/assets/f0c914cb-49b8-47fd-80f4-f00aab77878b">
Thank you. What should I do to fix this problem?

> You need to run your backend with poetry run uvicorn main:app --reload --port 7001 in a separate console tab

**Comment by Web3Worlds** [comment]
Same problem

**Comment by abi** [comment]
This happens because ffmpeg isn't installed isn't on your system. I think you can remove the videopy dependency if you don't need to use video to code. Or you can install ffmpeg. Let me know if that fixes your issue.

**Comment by Web3Worlds** [comment]
![photo_2024-07-18_16-39-49](https://github.com/user-attachments/assets/e2acee52-a373-4381-896c-cc2b492887ff)
![photo_2024-07-18_16-39-37](https://github.com/user-attachments/assets/7565e28e-8045-4f9f-9e24-78c4d0adb179)
![photo_2024-07-18_16-37-05](https://github.com/user-attachments/assets/f1f1a0fc-ec43-426d-9dd3-a3807e07952a)


I have ffmpeg

**Comment by abi** [comment]
Ah I think, for you @Web3Worlds  this is the issue with the tempfile saving. More context but don't have a solution at the moment: https://github.com/abi/screenshot-to-code/issues/311

**Comment by Belka-kate** [comment]
> This happens because ffmpeg isn't installed isn't on your system. I think you can remove the videopy dependency if you don't need to use video to code. Or you can install ffmpeg. Let me know if that fixes your issue.

It fixed the issue but there is news one. Error is the same :(
<img width="1440" alt="Снимок экрана 2024-07-19 в 23 39 31" src="https://github.com/user-attachments/assets/69d78eb4-2a61-49e8-b395-45aede063aec">
<img width="1440" alt="Снимок экрана 2024-07-19 в 23 40 49" src="https://github.com/user-attachments/assets/6ec1276c-22d5-45b0-b9d5-6d8adeb3d44a">
![Uploading Снимок экрана 2024-07-19 в 23.40.59.png…]()

**Comment by abi** [comment]
Is your Anthropic API key correct? It seems like Anthropic is responding with "Request not allowed"

**Comment by pymdashen** [comment]
same problem

**Comment by pymdashen** [comment]
![image](https://github.com/user-attachments/assets/ef419006-d617-4d66-a528-1c1e5d9bcaeb)

**Comment by abi** [comment]
@pymdashen Please open a new issue and share your logs so I can help you.

**Comment by pymdashen** [comment]
![image](https://github.com/user-attachments/assets/df7864a3-5dc5-44bc-b685-3d872e929191)

**Comment by abi** [comment]
As I mentioned, please open a new issue to avoid derailing this issue.

**Comment by Belka-kate** [comment]
> Is your Anthropic API key correct? It seems like Anthropic is responding with "Request not allowed"

I fixed it and now it works, thank you <3
