### ISSUE TITLE
Substitute image generation with Dall-e to placeholders

### ISSUE THREAD

**Issue by larstton** [abi/screenshot-to-code#379]
Now the images are generated using Dall-e

Is possible to disable the image generation and use just placeholders?

I saw this functionality in one of the videos you have provided but I can't find how to do it. 

The generation with dalle consumes tokens for no reason.

**Comment by abi** [comment]
<img width="568" alt="Screenshot 2024-07-26 at 12 44 34 PM" src="https://github.com/user-attachments/assets/1ef2ea1b-aef3-4da0-8d28-b30145f7beef">

If you open up settings, there's a toggle.

**Comment by abi** [comment]
Feel free to close the ticket if this answers your question

**Comment by larstton** [comment]
Omg, I am blind :D Thank you.
