### ISSUE TITLE
can't install says no file folder found for backend

### ISSUE THREAD

**Issue by WethersPulseMedia** [abi/screenshot-to-code#382]
I try poetry install in the backend folder and am greeted with this message:

![image](https://github.com/user-attachments/assets/c11d4c34-83ee-43ca-8d4c-019aaea61f92)

**Comment by WethersPulseMedia** [comment]
finally got past that but received this error when I tried to run the backend.  any ideas?

![image](https://github.com/user-attachments/assets/35b196c7-6cbd-4259-88a6-b364ebad891f)

**Comment by abi** [comment]
That is strange. Is there a main.py in the folder you're running the command from?

You could also try python start.py and see if that works. And what happens when visit the URL 127.0.0.1:7000?

**Comment by WethersPulseMedia** [comment]
Yeah there is main.py in the folder, I cloned the git repo so it should all be identical. When I try to visit the local link it just says it is unreachable. I will try python start and see if that works and report back! Thanks

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by WethersPulseMedia** [comment]
python start didn't work this is what happened? any ideas? 
![image](https://github.com/user-attachments/assets/069f06fd-f771-43fb-8be9-c8c42d9f8598)

**Comment by WethersPulseMedia** [comment]
I did have to change the folder structure slightly due to Poetry saying the backend wasn't a package so I created another backend folder within Backend that hosts all of the main .py  files which allowed me to bypass the initial error I submitted above. 

![image](https://github.com/user-attachments/assets/b8273562-e3c3-43db-8857-c2c6dffcee58)

**Comment by WethersPulseMedia** [comment]
okay, i solved the issue! it was Python 3.12.4. for some reason, this is a common error and the suggested method is to roll back to Python 3.12.3 and that fixed my issue! just want to make this known!
![image](https://github.com/user-attachments/assets/ab7672ad-fb99-4d7b-86c1-01253292b6cd)

**Comment by WethersPulseMedia** [comment]
thank you!
