### ISSUE TITLE
Type Error on backend

### ISSUE THREAD

**Issue by Tenkung5674-1234** [abi/screenshot-to-code#385]
<img width="1311" alt="Screenshot 2024-08-07 at 12 58 49 AM" src="https://github.com/user-attachments/assets/1a935978-9220-4f34-bdd0-08bddc866c42">

It gives me this error when try to run backend and follow the instructions on Readme.

**Comment by abi** [comment]
Try downgrading your Python version. There's an issue with the Pydantic package.

**Comment by Tenkung5674-1234** [comment]
> Try downgrading your Python version. There's an issue with the Pydantic package.

What is the recommended version for Python?

**Comment by Tenkung5674-1234** [comment]
> Try downgrading your Python version. There's an issue with the Pydantic package.

Fixed Thank you
