### ISSUE TITLE
WebSocket error code, After uploading the screenshot. 

### ISSUE THREAD

**Issue by KamleshKumar427** [abi/screenshot-to-code#39]
CloseEvent {isTrusted: true, wasClean: false, code: 1006, reason: '', type: 'close', …}

![image](https://github.com/abi/screenshot-to-code/assets/95052507/5a3aece5-354d-49bc-987b-1a5bc00e28fb)

**Comment by abi** [comment]
Thanks for reporting this! Please running the code locally on your computer instead, and let me know what the backend output is. I'm not debugging issues with the hosted version at the moment.
