### ISSUE TITLE
Cant‘t Open ScreenShottoCode paid html

### ISSUE THREAD

**Issue by CharlesZhang2023** [abi/screenshot-to-code#409]
**Describe the bug**

**To Reproduce**

**Screenshots of backend AND frontend terminal logs**

**Comment by abi** [comment]
What’s the issue you are facing?

**Comment by CharlesZhang2023** [comment]
I subscribed the Screenshot-to-code paid service ,but I can't open the https://screenshottocode.com/ website now
<img width="1310" alt="Screenshot 2024-10-10 at 15 43 55" src="https://github.com/user-attachments/assets/3b698dea-75be-4bde-b79e-dfaed9abe16b">

**Comment by CharlesZhang2023** [comment]
I subscribe to this service every month but now nothing is working please fix it quickly. If not, please assistant me cancel the monthly subscribe, now the website can't be access, thanks.

**Comment by abi** [comment]
@CharlesZhang2023 sorry about that. Can you try a VPN? I'm also happy to cancel your subscription if you email me your account information (more private over email than Github). Please see the email in my profile: https://github.com/abi

**Comment by CharlesZhang2023** [comment]
Okay,  I have sent my account information will email, Please help me cancel the plan, Thanks!

**Comment by abi** [comment]
Responded by email!
