### ISSUE TITLE
Hallucination 

### ISSUE THREAD

**Issue by lionelcoding** [abi/screenshot-to-code#448]
Describe the bug
When using Screenshot to Code, the generated code output is incorrect/hallucinates and does not accurately match the expected layout and components of the original screenshot. The AI seems to be generating a news website layout instead of a Google Meet interface.

To Reproduce

Go to Screenshot to Code interface
Upload a screenshot of Google Meet interface
Select "HTML + Tailwind" as the generation option
Click "Update" or "Regenerate"
Observe that the generated result shows a news website layout with articles about "Israeli Military Raids" and "Las Vegas Weddings" instead of the Google Meet interface components
Screenshots of backend AND frontend terminal logs
From the provided screenshot, we can see:

Input: Google Meet interface screenshot showing a video call interface with control buttons and a participant
Output: Incorrectly generated layout showing a news website with unrelated content
The generation settings show "HTML + Tailwind" is selected
No terminal logs are visible in the provided screenshot to help debug the issue
Additional notes:

This appears to be a model hallucination issue where the AI is not correctly interpreting the input screenshot
The generated layout is completely different from the source material (Google Meet interface)
The issue seems to be with the model's interpretation rather than a technical error, as the generation process completes but produces incorrect results
![CleanShot 2024-12-02 at 00 57 12@2x](https://github.com/user-attachments/assets/d13ca3ae-9583-41f9-b185-e66c8f5f918b)

**Comment by abi** [comment]
Do you have the SHOULD_MOCK_AI_RESPONSE env variable set in your backend .env file?  The response here is a mock response that is used for testing during development.

**Comment by lionelcoding** [comment]
No, I've only made a git clone of this repo and followed the README instructions.

**Comment by abi** [comment]
@lionelcoding I'll look into this. Can you share your .env after taking out the keys?

You can also go into the config.py in backend and change the SHOULD_MOCK_AI_RESPONSE = line to "SHOULD_MOCK_AI_RESPONSE=False". Let me know if that works.

**Comment by lionelcoding** [comment]
Should_mock_AI_RESPONSE was already on False.

![CleanShot 2024-12-02 at 16 23 34@2x](https://github.com/user-attachments/assets/f2440a12-90b9-4021-a9fe-4a77d346381f)

**Comment by lionelcoding** [comment]
@abi here my content into .env file 

`OPENAI_API_KEY=xxxxxx
`
Thanks

**Comment by abi** [comment]
Change the line to "SHOULD_MOCK_AI_RESPONSE=False" and see it helps.

**Comment by lionelcoding** [comment]
It works thanks. I touched the Anthropic SDK integration in llm.py as well.

**Comment by abi** [comment]
@lionelcoding how did you modify llm.py?

**Comment by abi** [comment]
I'm pretty surprised you ran into this because it shouldn't happen unless the env var is set.

**Comment by lionelcoding** [comment]
@abi sorry I mean I noticed the Anthropic package is missing. I've only run the poetry add anthropic@latest command in my terminal.
