### ISSUE TITLE
New ChatGpt-4o-2024-11-20

### ISSUE THREAD

**Issue by brunogcpinheiro** [abi/screenshot-to-code#459]
I'm facing an error that I believe is new due to the recent changes. It gives this error and falls into the all_generations_failed error exception.

`Error code: 404 - {'error': {'message': 'The model `gpt-4o-2024-11-20` does not exist or you do not have access to it.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}`

![image](https://github.com/user-attachments/assets/5faf928f-28fb-46a4-9988-556c76b404c7)

**Comment by abi** [comment]
How did you resolve it? I think all OpenAI accounts with some credit should have access to this model.
