### ISSUE TITLE
。。。。

### ISSUE THREAD

**Issue by lwweee** [abi/screenshot-to-code#469]
Shortly after GPT came out, I learned about this website from Bilibili's video, then paid for it for a month, and then found a very simple web page. The code generated by it and the expected effect were very poor, which gave me the feeling of being like the IQ level of GPT3.5. Now, let's recall that GPT3.5 was available at that time. What factors influenced me to pay for this AI-based service? . . . . . .

**Comment by abi** [comment]
I appreciate the feedback. The models are much better now!
