### ISSUE TITLE
Remove Nine-dash line image from repository description

### ISSUE THREAD

**Issue by hblab-khoipv** [abi/screenshot-to-code#49]
I think you should edit the illustration on your repository. Nine-dash line is not recognized internationally, I don't know if you did it intentionally or unintentionally. This is not true
![image](https://github.com/abi/screenshot-to-code/assets/80022539/7e4d3867-b686-4587-b969-186258e1c684)
![image](https://github.com/abi/screenshot-to-code/assets/80022539/f2b3fde4-56a3-4dd2-83bd-9aece7131166)

**Comment by abi** [comment]
Yeah, not intentional. That was just the top story on the NYtimes that day. Will update.

**Comment by abi** [comment]
updated

**Comment by hblab-khoipv** [comment]
Thank you very much
