### ISSUE TITLE
Support uploading pdfs

### ISSUE THREAD

**Issue by NaorFirefly** [abi/screenshot-to-code#52]
Hi, would that be possible? Thanks

**Comment by abi** [comment]
Can you share your use case? What is it that you're looking to convert?

Looking to support.

**Comment by NaorFirefly** [comment]
A pdf of text mixed with graphics just to text
Each page should be converted to an image
Then to html
And then unify pdf

**Comment by abi** [comment]
@NaorFirefly thanks. What kind of PDFs are they?

**Comment by NaorFirefly** [comment]
Magazine for example. So when I do it manually it works very well
Just screenshot per page, then I input to the tool, get HTML, ask "without
pictures, one column", then I download the HTML, convert to PDF (with
printing into PDF), and then unify the PDFs. Then I convert to EPUB and I
have a magazine of PDF -> EPUB ready for Kindle.

**Comment by clean99** [comment]
Before supporting PDF upload, multi-image upload should be supported given that PDF typically contains more than one image.

**Comment by abi** [comment]
@NaorFirefly that workflow makes sense. I'm not going to work on this but others are free to take this up. Should be relatively easy to add.

@clean99 makes sense. For PDF, there should be a bunch of JS libraries like pdf.js that should be able to convert PDF into a set of images.

**Comment by NaorFirefly** [comment]
Can you at least add the multi image upload?
The other parts are easy

**Comment by PiyushMishra318** [comment]
@abi I want to work on this issue. Just needed clarifications on a couple of things.

**Issue**:  Currently the application does not support pdf uploads.

**Possible Solution**:
First of all, add support to upload pdfs which in turn will convert the each page to a separate image. 

We can do this on frontend or backend. Let me know which one you'd prefer. I would suggest just giving multi image support  to the frontend to begin. Then we might have to generate results for each image separately because of the limited context for openAI API.

**Comment by NaorFirefly** [comment]
Multi-image sounds great to begin with!! thank you

**Comment by abi** [comment]
@PiyushMishra318 I would start with the simplest thing possible: accept multiple images and send them all in one request. Let's not worry about context for now. Input is 128K and output is 4K so input is really not a concern.

**Comment by PiyushMishra318** [comment]
@abi Got it. I'll submit a PR in a couple days.

**Comment by NaorFirefly** [comment]
Hi @PiyushMishra318 any news? Cheers

**Comment by PiyushMishra318** [comment]
@NaorFirefly  You can follow [#84](https://github.com/abi/screenshot-to-code/pull/84) PR for updates.

**Comment by abi** [comment]
I will take a look shortly.
