### ISSUE TITLE
Add reset button in error state and stop button when coding

### ISSUE THREAD

**Issue by clean99** [abi/screenshot-to-code#60]
Now when we finish uploading an image, there is no way to upload a new image unless users open a new window. Considering adding an escape capsule or embedding the upload new image feature after users upload an image.

**Comment by clean99** [comment]
Yes, what I mean is the reset button, sorry I miss the button

**Comment by abi** [comment]
One thing that would be nice is to show the reset button when the code is generating. Right now, if you get an error during generation, you have to refresh the page. Could call it a "Stop" button when code is generating, and keep it "Reset" during error or success state.
