### ISSUE TITLE
Question!

### ISSUE THREAD

**Issue by dominicdev** [abi/screenshot-to-code#68]
its it possible to deploy this in google cloud? 
I tried to run this in google computer engine but seems cant find to the websocket, it runs but can get tp  generate code

**Comment by Laixinsz** [comment]
I am also deployed in Google Cloud. I access it through Nginx reverse proxy. The front-end access is normal, but an error will be reported when generating.
error message:
Connecting to backend @ ws://127.0.0.1:7001/generate-code
generateCode.ts:24 WebSocket connection to 'ws://127.0.0.1:7001/generate-code' failed:
generateCode @generateCode.ts:24
generateCode.ts:55 WebSocket error Event
(anonymous) @generateCode.ts:55
generateCode.ts:45 Connection closed 1006
generateCode.ts:47 WebSocket error code CloseEvent

My nginx reverse proxy configuration is as follows:

server {
listen 80;
server_name my.com;

location/{
proxy_pass http://localhost:5173;
proxy_http_version 1.1;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection 'upgrade';
proxy_set_header Host $host;
proxy_cache_bypass $http_upgrade;
}

location /generate-code {
proxy_pass http://127.0.0.1:7001;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "Upgrade";
proxy_set_header Host $host;
add_header Access-Control-Allow-Origin *;
add_header Access-Control-Allow-Headers *;
}
}
Please let me know if you find a fix
Thanks.

**Comment by abi** [comment]
Closing this issue since I can't help debug Google Cloud issues. But if anyone has suggestions, please add.
