### ISSUE TITLE
Deployed on the server, reporting errors through reverse proxy backend

### ISSUE THREAD

**Issue by Laixinsz** [abi/screenshot-to-code#69]
Deployed in Google Cloud, accessed through Nginx reverse proxy. Front-end access is normal, but an error will be reported when generating.
error message:
![iShot_2023-11-21_19 49 32](https://github.com/abi/screenshot-to-code/assets/69241339/a1e5442c-a1dd-44dd-ae05-4716b4f80621)

Connecting to backend @ ws://127.0.0.1:7001/generate-code
generateCode.ts:24 WebSocket connection to 'ws://127.0.0.1:7001/generate-code' failed:
generateCode @generateCode.ts:24
generateCode.ts:55 WebSocket error Event
(anonymous) @generateCode.ts:55
generateCode.ts:45 Connection closed 1006
generateCode.ts:47 WebSocket error code CloseEvent

My nginx reverse proxy configuration is as follows:
server {
listen 80;
server_name my.com;

location/{
proxy_pass http://localhost:5173;
proxy_http_version 1.1;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection 'upgrade';
proxy_set_header Host $host;
proxy_cache_bypass $http_upgrade;
}

location /generate-code {
proxy_pass http://127.0.0.1:7001;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "Upgrade";
proxy_set_header Host $host;
add_header Access-Control-Allow-Origin *;
add_header Access-Control-Allow-Headers *;
}
}
Please tell me how to solve it. It is a very good open source program. Thank you!

**Comment by samya123456** [comment]
can you try this to make your backend up and running 
poetry run uvicorn main:app --host 0.0.0.0 --reload --port 7001

**Comment by nzd520** [comment]
> can you try this to make your backend up and running poetry run uvicorn main:app --host 0.0.0.0 --reload --port 7001

it can not work

**Comment by Laixinsz** [comment]
> 你可以尝试这个让你的后端启动并运行 诗歌运行 uvicorn main:app --host 0.0.0.0 --reload --port 7001
I'm running it on Docker, so I don't need this step.
