### ISSUE TITLE
Plans for an hosted/SaaS version?

### ISSUE THREAD

**Issue by adelowo** [abi/screenshot-to-code#71]
Hi,

I was wondering if there are plans to make an hosted version/SaaS as I currently do not have access to the GPT4 Vision product :)

**Comment by abi** [comment]
Thanks for the feedback! Are you looking to use this for work?

**Comment by adelowo** [comment]
Not at all. Personal use case for micro projects I work on - but obviously happy to pay

**Comment by abi** [comment]
Nice! How many screenshots do you think you'd use per month?

**Comment by adelowo** [comment]
30-50 I suppose

**Comment by abi** [comment]
Thanks for the feedback. Will consider adding a Saas version.

**Comment by abi** [comment]
Don't have a full SaaS version but you can now buy credits on https://screenshottocode.com so anyone that can't get the key themselves can buy some credits

**Comment by adelowo** [comment]
thanks!
