### ISSUE TITLE
What's happening here?

### ISSUE THREAD

**Issue by hkcitizens9527** [abi/screenshot-to-code#72]
**can't generate** 
![13123131](https://github.com/abi/screenshot-to-code/assets/100154726/fb93ce16-62ae-4db3-b6f7-69b55bfdaf2c)

**Comment by abi** [comment]
Might be an issue with your port: try 7001 for backend: poetry run uvicorn main:app --reload --port 7001

**Comment by CherishMvp** [comment]
你使用的key三官方买的吗？

**Comment by hkcitizens9527** [comment]
> 你使用的key三官方买的吗？

Genuine, I bought Chat GPT Plus

**Comment by abi** [comment]
@hkcitizens9527 you need to get some credits for the API. Please see FAQ

**Comment by NgXuanKhoa** [comment]
> @hkcitizens9527bạn cần nhận được một số tín hiệu cho API. Vui lòng xem câu hỏi thường gặp

![image](https://github.com/abi/screenshot-to-code/assets/120007712/02dad756-a011-4e6c-a3da-2fcaa472e5c7)
I have the problem as shown in the photo

**Comment by JackHeeney** [comment]
mine gets this error like 20 times and then proceeds to attempt the write the code... usually it does it half right and then i try to use the AI to edit parts and it just displays the exact same result without the edits i asked for.

**Comment by choutassou** [comment]
I got the API key worked on sample site, and failed in my local pc.
But, the port "7001" saved me magically. thank you.
