### ISSUE TITLE
can't run fronted because node version incompatible

### ISSUE THREAD

**Issue by yoyoballyoyo** [abi/screenshot-to-code#75]
I run the project on windows, and built a anaconda env with python 3.11, every essential requirements were installed, backend runs successfullly, however, when i try to run frontend and run yarn command, things come up with this：

yarn install v1.22.19
[1/5] Validating package.json...
error screenshot-to-code@0.0.0: The engine "node" is incompatible with this module. Expected version ">=14.18.0". Got "6.10.3"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

when i try to pip upgrade node with version==14.18.0. it comes with:

ERROR: Could not find a version that satisfies the requirement node==14.18.0 (from versions: 0.9, 0.9.1, 0.9.2, 0.9.3, 0.9.4, 0.9.5, 0.9.6, 0.9.7, 0.9.8, 0.9.9, 0.9.10, 0.9.11, 0.9.12, 0.9.13, 0.9.14, 0.9.15, 0.9.16, 0.9.17, 0.9.18, 0.9.18.1, 0.9.19, 0.9.20, 0.9.21, 0.9.22, 0.9.23, 0.9.24, 0.9.25, 0.9.26, 0.9.27, 0.9.28, 1.0, 1.1, 1.2, 1.2.1)
ERROR: No matching distribution found for node==14.18.0

how to solve this issue? pls help

**Comment by mosamdabhi** [comment]
Any update? How did you solve this?
