### ISSUE TITLE
Access Denied: Model Not Found

### ISSUE THREAD

**Issue by cmarin001** [abi/screenshot-to-code#77]
I encountered an error when attempting to access the gpt-4-vision-preview model. The system responded with an error message indicating that the model either does not exist or is not accessible with my current permissions.

![image](https://github.com/abi/screenshot-to-code/assets/45011420/da027860-b3c8-478a-afe1-e9e1597977fb)

but I'm sure that I get access to the gtp-plus
![image](https://github.com/abi/screenshot-to-code/assets/45011420/70222909-3574-456f-8833-0bdf76ac5218)
 
And I've created the key correctly
![image](https://github.com/abi/screenshot-to-code/assets/45011420/f5a9323f-e180-4872-bf7b-0be7160db219)

**Comment by abi** [comment]
Please see the FAQ: https://github.com/abi/screenshot-to-code#%EF%B8%8F-faqs

**Comment by abi** [comment]
You need to buy $1 of credit.

**Comment by 18984955240** [comment]
> You need to buy $1 of credit.

Sorry, Do you buy it here? I want to make sure I'm in the right place
![0C0163F7-8F77-483A-922F-C6E776B39AF9](https://github.com/abi/screenshot-to-code/assets/16495539/df7bd9a8-50e8-4956-b520-60dd4dd07916)

**Comment by abi** [comment]
Yeah if you have $5, you might already have access to the model.
