### ISSUE TITLE
help！！Error generating code

### ISSUE THREAD

**Issue by mimoon200807** [abi/screenshot-to-code#86]
popup displays the error 'Error generating code. Check the Developer Console for details. Feel free to open a Github issue'

**Comment by bamboo-yujiro** [comment]
I encountered the same issue. In my case, when I checked the Developer Console, the only message I saw was that the WebSocket had closed. So, I entered the backend container and manually started the server:

```bash
$ docker-compose exec backend bash
$ poetry run uvicorn main:app --host 0.0.0.0 --port ${BACKEND_PORT:-7001}
```

Doing this, an exception was thrown. In my case, it was:

```
openai.RateLimitError: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}
```

So, I had exceeded the API key usage limit.


Therefore, I recommend first opening the Developer Console and, if the detailed cause is not clear like in my case, entering the backend container, starting the server, and checking the logs.

**Comment by abi** [comment]
@bamboo-yujiro exactly. I updated the error message to tell people to check the backend logs. Hard to debug without backend logs.
