### ISSUE TITLE
The model `gpt-4-vision-preview` does not exist or you do not have access to it

### ISSUE THREAD

**Issue by piruthivi3232** [abi/screenshot-to-code#88]
![Screenshot 2023-11-23 at 6 35 03 PM](https://github.com/abi/screenshot-to-code/assets/137818127/fc02f391-2617-43e5-9f99-a1a296432e58)
![Screenshot 2023-11-23 at 6 35 12 PM](https://github.com/abi/screenshot-to-code/assets/137818127/cd6e0cba-7fd4-4cca-afc3-24750cc0b585)

**Comment by abi** [comment]
See https://github.com/abi/screenshot-to-code#%EF%B8%8F-faqs
