### ISSUE TITLE
AI doesn't produce full code for the screenshot

### ISSUE THREAD

**Issue by JackHeeney** [abi/screenshot-to-code#90]
mine gets this error like 20 times and then proceeds to attempt the write the code... usually it does it half right and then i try to use the AI to edit parts it forgets the code it previously wrote and only gives back what i asked to be edited.

![image_2023-11-23_133453946](https://github.com/abi/screenshot-to-code/assets/23397891/c32a1593-9708-499f-b53d-36719f7f1fc1)
_Attempting code but throwing errors_

![image_2023-11-23_133539919](https://github.com/abi/screenshot-to-code/assets/23397891/e9ef96c3-893c-4b00-9b3f-9049f9afd2aa)
_End result_

![image](https://github.com/abi/screenshot-to-code/assets/23397891/c2b00423-0e38-47f7-a361-1d186bd9fd41)
_Attempting edit_

![image_2023-11-23_133659676](https://github.com/abi/screenshot-to-code/assets/23397891/03b88bf3-b007-40fe-bdca-da2922d5faa2)
_Result only produced the navbar but left off the original code it had already created_

**Comment by abi** [comment]
Yeah, making it not insert placeholders for the previous code is a real challenge. What I would recommend is combining the code by hand.

Once GPT4 vision is out of preview, we'll try other strategies to avoid this problem.

**Comment by abi** [comment]
Should be solved with GPT4o now.
