### ISSUE TITLE
screenshot is not entirely processed

### ISSUE THREAD

**Issue by MaraScott** [abi/screenshot-to-code#91]
When executing screenshot to html (which is an awesome tools everybody is looking for), from this

![download](https://github.com/abi/screenshot-to-code/assets/482210/8cf88f22-2b90-4201-90f8-da76dc7f7085)

I got this

![Web capture_23-11-2023_215523_](https://github.com/abi/screenshot-to-code/assets/482210/e8aa285d-8cfb-4c55-8840-26cd8fcaafe7)

Any idea what s going on ?

**Comment by abi** [comment]
Yeah this is a common issue. GPT Vision can sometimes be lazy. I would retry because some outputs will be better than others.

**Comment by abi** [comment]
Also think when they do release a non-preview model, it'll be easier to work around these issues with prompting. Right now the model seems to change on a daily basis.

**Comment by davask** [comment]
Do you have a timeline for `when they do release a non-preview model` ?

**Comment by abi** [comment]
No OpenAI hasn't communicated that but my guess is a few weeks.

**Comment by abi** [comment]
The result is a lot better with GPT4o. We continue to improve the quality as well so I'm closing this specific older issue

![screencapture-a-picoapps-xyz-five-current-2024-05-21-13_37_48](https://github.com/abi/screenshot-to-code/assets/23818/7290723c-618e-4b4f-a739-6fc466ecd20d)
