### ISSUE TITLE
The model `gpt-4-vision-preview` does not exist or you do not have access to it

### ISSUE THREAD

**Issue by piruthivi3232** [abi/screenshot-to-code#92]
![Screenshot 2023-11-24 at 7 07 19 AM](https://github.com/abi/screenshot-to-code/assets/137818127/3d1c3d40-3a1d-475b-8aba-bbfba8245d00)
![Screenshot 2023-11-24 at 7 07 36 AM](https://github.com/abi/screenshot-to-code/assets/137818127/0f233837-8bda-4283-ae5e-d713693019ef)
I have followed https://github.com/abi/screenshot-to-code#%EF%B8%8F-faqs this also it's not working same issue.

**Comment by abi** [comment]
All can I suggest is to follow: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4 and double check you're using the right API key. If it still doesn't work, then contact OpenAI support.
