### ISSUE TITLE
No errors when uploading screenshots, but no code is being generated, see logs attached

### ISSUE THREAD

**Issue by EDWINCHENC** [abi/screenshot-to-code#95]
The Docker image was built successfully and is running fine. There are no errors when uploading screenshots, but no code is being generated... What could be the reason? Below are the docker-compose logs:

![1](https://github.com/abi/screenshot-to-code/assets/130730471/aa42f266-55f4-41b0-955c-9439e70724e9)
![2](https://github.com/abi/screenshot-to-code/assets/130730471/52ed6657-3750-4977-bd6c-3df0c06f911f)
![3](https://github.com/abi/screenshot-to-code/assets/130730471/4d0a9921-71e3-4bff-8201-8f6d1963d459)

**Comment by EDWINCHENC** [comment]
is it because I use the base_url instead of official api ?  I am sure the base_url works in other condition

**Comment by LaomoHans** [comment]
You need to add v1 after your transfer URL, such as https://xxx.xxxx.xxxx/v1, give it a try

**Comment by abi** [comment]
Closing during to inactivity
