### ISSUE TITLE
Support for react/vue/svelte?

### ISSUE THREAD

**Issue by egeres** [abi/screenshot-to-code#96]
I've been ~wasting money for fun~ testing the project with some websites and it's really interesting. But right now, besides doing quick mockups, I see little applicability in real-life scenarios since raw HTML doesn't provide a workflow where you can easily compose with structures, parse information from a request and what not

**Are there any plans on giving support for any of the major front-end frameworks? (Vue, React, Svelte...)**

I wonder if it could be as simple as asking the model to then parse the output HTML into something else. Or, if on the other hand, there would be an advantage at directly asking the model to refactor code on the fly to create a more optimal structure...

**Comment by abi** [comment]
Yes, it should be relatively simple and we do plan to add that in the future.

**Comment by clean99** [comment]
I will do this in the weekend.

**Comment by zhengdechang** [comment]
I think this is still a bit difficult, because react and vue need to be converted to html to preview, which makes the production effect slow

**Comment by dialmedu** [comment]
Related to workflows, i achieved this by experimenting with the JavaScript language, `with javascript add one button to header for tooggle theme white to black`, this has add icon the moon and sun for respresent color theme this recognize the use this strategi UX in then web.

![prueba_toogle_theme](https://github.com/abi/screenshot-to-code/assets/8028861/5f699a14-112a-4402-b3ae-3e2639a67d95)

Here test call api in [pokemon.api ](https://pokeapi.co/) the message write exactly get data image , for print result write `in profile image use data.sprites.frond_default` becose It's not readily apparent how get image data for humans with this api, perhaps Gpt can recognize it :smile: 
![prueba_call_api](https://github.com/abi/screenshot-to-code/assets/8028861/a9587060-3733-466a-9222-e812a41fa986)

*Interesting add support for apis for create interactive results.*

**Comment by HongyiInstalily** [comment]
> Related to workflows, i achieved this by experimenting with the JavaScript language and Vuejs, `with javascript add one button to header for tooggle theme white to black`, this has add icon the moon and sun for respresent color theme this recognize the use this strategi UX in then web.
> 
> ![prueba_toogle_theme](https://private-user-images.githubusercontent.com/8028861/285599506-0a2a96ec-956a-4765-94a9-46ef98fb9093.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExMjI2MTIsIm5iZiI6MTcwMTEyMjMxMiwicGF0aCI6Ii84MDI4ODYxLzI4NTU5OTUwNi0wYTJhOTZlYy05NTZhLTQ3NjUtOTRhOS00NmVmOThmYjkwOTMuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTEyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzExMjdUMjE1ODMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjQ0MzU5ZmIwYzY0NzFmYzY1Y2IyNDlhOThlY2I4MDlmMWQyYjMzNmI1YTFiNWM3YzFjMDdhZTc2NTc3NWEzNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ZCI_HWn4uQgI4ZyX_CrQnvC7TaLxC7BJZwPlcaPa1jM) [ ![prueba_toogle_theme](https://private-user-images.githubusercontent.com/8028861/285599506-0a2a96ec-956a-4765-94a9-46ef98fb9093.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExMjI2MTIsIm5iZiI6MTcwMTEyMjMxMiwicGF0aCI6Ii84MDI4ODYxLzI4NTU5OTUwNi0wYTJhOTZlYy05NTZhLTQ3NjUtOTRhOS00NmVmOThmYjkwOTMuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTEyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzExMjdUMjE1ODMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjQ0MzU5ZmIwYzY0NzFmYzY1Y2IyNDlhOThlY2I4MDlmMWQyYjMzNmI1YTFiNWM3YzFjMDdhZTc2NTc3NWEzNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ZCI_HWn4uQgI4ZyX_CrQnvC7TaLxC7BJZwPlcaPa1jM) ](https://private-user-images.githubusercontent.com/8028861/285599506-0a2a96ec-956a-4765-94a9-46ef98fb9093.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExMjI2MTIsIm5iZiI6MTcwMTEyMjMxMiwicGF0aCI6Ii84MDI4ODYxLzI4NTU5OTUwNi0wYTJhOTZlYy05NTZhLTQ3NjUtOTRhOS00NmVmOThmYjkwOTMuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTEyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzExMjdUMjE1ODMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjQ0MzU5ZmIwYzY0NzFmYzY1Y2IyNDlhOThlY2I4MDlmMWQyYjMzNmI1YTFiNWM3YzFjMDdhZTc2NTc3NWEzNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ZCI_HWn4uQgI4ZyX_CrQnvC7TaLxC7BJZwPlcaPa1jM) [ ](https://private-user-images.githubusercontent.com/8028861/285599506-0a2a96ec-956a-4765-94a9-46ef98fb9093.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExMjI2MTIsIm5iZiI6MTcwMTEyMjMxMiwicGF0aCI6Ii84MDI4ODYxLzI4NTU5OTUwNi0wYTJhOTZlYy05NTZhLTQ3NjUtOTRhOS00NmVmOThmYjkwOTMuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTEyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzExMjdUMjE1ODMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjQ0MzU5ZmIwYzY0NzFmYzY1Y2IyNDlhOThlY2I4MDlmMWQyYjMzNmI1YTFiNWM3YzFjMDdhZTc2NTc3NWEzNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ZCI_HWn4uQgI4ZyX_CrQnvC7TaLxC7BJZwPlcaPa1jM)
> 
> Here test call api in [pokemon.api ](https://pokeapi.co/) the message write exactly get data image , for print result write `in profile image use data.sprites.frond_default` becose It's not readily apparent how get image data for humans with this api, perhaps Gpt can recognize it 😄 ![prueba_call_api](https://private-user-images.githubusercontent.com/8028861/285596655-a9587060-3733-466a-9222-e812a41fa986.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExMjI2MTIsIm5iZiI6MTcwMTEyMjMxMiwicGF0aCI6Ii84MDI4ODYxLzI4NTU5NjY1NS1hOTU4NzA2MC0zNzMzLTQ2NmEtOTIyMi1lODEyYTQxZmE5ODYuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTEyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzExMjdUMjE1ODMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDM5NmM3MWFhMjUyOTFhMTUxMjQ1NTIyMmYzNmQwM2IzMDhmNThhMDZhN2E1ZDY2ZmIwM2Y4MDg3OWZkYzZkNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Dn0n-VGP-uZypzlR9RBVtQJOC6b0x6lw6-nGrUkW0Nc) [ ![prueba_call_api](https://private-user-images.githubusercontent.com/8028861/285596655-a9587060-3733-466a-9222-e812a41fa986.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExMjI2MTIsIm5iZiI6MTcwMTEyMjMxMiwicGF0aCI6Ii84MDI4ODYxLzI4NTU5NjY1NS1hOTU4NzA2MC0zNzMzLTQ2NmEtOTIyMi1lODEyYTQxZmE5ODYuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTEyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzExMjdUMjE1ODMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDM5NmM3MWFhMjUyOTFhMTUxMjQ1NTIyMmYzNmQwM2IzMDhmNThhMDZhN2E1ZDY2ZmIwM2Y4MDg3OWZkYzZkNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Dn0n-VGP-uZypzlR9RBVtQJOC6b0x6lw6-nGrUkW0Nc) ](https://private-user-images.githubusercontent.com/8028861/285596655-a9587060-3733-466a-9222-e812a41fa986.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExMjI2MTIsIm5iZiI6MTcwMTEyMjMxMiwicGF0aCI6Ii84MDI4ODYxLzI4NTU5NjY1NS1hOTU4NzA2MC0zNzMzLTQ2NmEtOTIyMi1lODEyYTQxZmE5ODYuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTEyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzExMjdUMjE1ODMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDM5NmM3MWFhMjUyOTFhMTUxMjQ1NTIyMmYzNmQwM2IzMDhmNThhMDZhN2E1ZDY2ZmIwM2Y4MDg3OWZkYzZkNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Dn0n-VGP-uZypzlR9RBVtQJOC6b0x6lw6-nGrUkW0Nc) [ ](https://private-user-images.githubusercontent.com/8028861/285596655-a9587060-3733-466a-9222-e812a41fa986.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExMjI2MTIsIm5iZiI6MTcwMTEyMjMxMiwicGF0aCI6Ii84MDI4ODYxLzI4NTU5NjY1NS1hOTU4NzA2MC0zNzMzLTQ2NmEtOTIyMi1lODEyYTQxZmE5ODYuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTEyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzExMjdUMjE1ODMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDM5NmM3MWFhMjUyOTFhMTUxMjQ1NTIyMmYzNmQwM2IzMDhmNThhMDZhN2E1ZDY2ZmIwM2Y4MDg3OWZkYzZkNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Dn0n-VGP-uZypzlR9RBVtQJOC6b0x6lw6-nGrUkW0Nc)
> 
> _Interesting add support for apis for create interactive results._

Could you please share the instructions for generating VueJS, as the current version can only generate HTML?  It would be really helpful.

**Comment by abi** [comment]
@HongyiInstalily going to try and get in support for Vue this week, but I think you modify the prompts in prompt.py based on something like https://michaelcurrin.github.io/code-cookbook/recipes/javascript/packages/vue/no-build-step.html, you might be able to get it working yourself.

**Comment by ExpressGit** [comment]
already generate react code,but cant show preview, why

**Comment by abi** [comment]
@ExpressGit there's a bug with React rendering where it sometimes doesn't work. If you switch between mobile and desktop, does it work?

**Comment by ralyodio** [comment]
I'd use it if svelte was supported.

**Comment by gusdoe** [comment]
One vote for svelte code generator
