### ISSUE TITLE
Error generating code. Check the Developer Console AND the backend logs for details. Feel free to open a Github issue.

### ISSUE THREAD

**Issue by 1309593444** [abi/screenshot-to-code#97]
Error generating code. Check the Developer Console AND the backend logs for details. Feel free to open a Github issue.

**Comment by abi** [comment]
Paste in the logs please.

**Comment by thornzz** [comment]
Hello abi,
I've downloaded 30 min ago docker version and build it with adding 
environment:
      - VITE_WS_BACKEND_URL=ws://192.168.xx.xx:7001 to compose file. 
![image](https://github.com/abi/screenshot-to-code/assets/31060482/32b0575d-0cb9-4e03-88d3-5db934ecaab1) 

Getting this error.

**Comment by abi** [comment]
@thornzz can you paste your docker logs (backend and front end)?

**Comment by JustPeders** [comment]
Hello abi,
I get the same error and it gives the same error in the dev console 
![image](https://github.com/abi/screenshot-to-code/assets/78874847/39133f60-8c1a-42eb-830c-6aa8f028551f)

**Comment by DarkJohnnyX** [comment]
same problem!help
<img width="527" alt="截屏2023-11-25 03 00 22" src="https://github.com/abi/screenshot-to-code/assets/134748980/fb02632a-060d-4d12-adfa-5cad5f23ef77">

**Comment by abi** [comment]
As mentioned above, need your backend logs to debug this effectively. Please paste that in.

**Comment by thornzz** [comment]
Sorry it was about my open api key. I have paid bill and it's fixed. Check Docker logs you can see the error.
